# Assignment 2. Data Science

This is the first assigment for the course. The idea is to get a deep understanding ofo Pandas library and get used to, in order to apply the same metodology for future work for _reading_, _manipulating_ and _cleaning_ datasets for **Machine Learning**.

### Part1: All Time Olympic Games Medals
Load the data set csv from "olympics.csv" using Pandas library.

First we need to import the library and load the file with the parameters we need in order to skip or set the way we the file is structured. Following the file looks like following

    0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
    ,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !,02 !,03 !,Total,№ Games,01 !,02 !,03 !,Combined total
    Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
    Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
    Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
    Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12

Seems we need to skip the first row, the other elements seems being accordingly to csv standard format.

In [1]:
import pandas as pd

In [221]:
df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

For the indexes we will be using the first column that it's the country.

Print the head of the read csv to see the results.

In [3]:
df.head()

,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !.1,02 !.1,03 !.1,Total.1,№ Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

Let's do what the assigment initially do with the dataframe

In [222]:
for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,AFG
Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,ALG
Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,ARG
Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,ARM
Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,ANZ

It's seems they are redefining some of the columns names (**Gold**, **Silver**, **Bronze**, etc..) and the countries names, so the are more suitable for managing by using indexing in python. This is to map each medal type depending on the session, so they will have unique columns name for indexing.

For the index, as we can see in the table above, we have the country names. As for the new **"ID"** column, the code of the country, within the brackets, it's being used. Also the column called total is deleted.

### Question 0

Let's we start with the initial (example) question. I have to create a function per question, that will return the expected value.

In [5]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero()

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

In [6]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.loc["Afghanistan"]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero()

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

### Question 1

Which country has won the most gold medals in summer games?

This function should return a single string value.

In [7]:
def answer_one():
    return "YOUR ANSWER HERE"

In order to return the country with most gold medals in summer games, we have to get the argmax of the values in the *"Gold"* column, from the _summer games session_.

First let's we take only the column we need by using indexing. In order to do that we are going to use dataframe indexing so  it's going to return a new view the the index and the column we need. Then we only have to apply a Numpy function that will return the max value. Then we hav to return the country name, that's it's going to be the index[0].

In [8]:
gms_df = df["Gold"]
gms_df.head()

Afghanistan     0
Algeria         5
Argentina      18
Armenia         1
Australasia     3
Name: Gold, dtype: int64

In [9]:
gms_argmax = df["Gold"].argmax()
print(gms_argmax)

United States

In [10]:
print(df["Gold"]["United States"])

976

We know that it's **"United states"** with **976** medals. Also we can sort the values within the dataframe by using that column values.

### Answer Question 1

In [11]:
def answer_one():
    return df["Gold"].argmax()
answer_one()

'United States'

### Question 2

Which country had the biggest difference between their summer and winter gold medal counts?

This function should return a single string value.

In [12]:
def answer_two():
    return "YOUR ANSWER HERE"

In order to get the biggest difference between summer and winter gold medals counts, we have to create additional column with this value in a view, and then use the same method we used in the question Nº 1.

In [13]:
gold_sw = df[["Gold","Gold.1"]]
gold_sw.head()

             Gold  Gold.1
Afghanistan     0       0
Algeria         5       0
Argentina      18       0
Armenia         1       0
Australasia     3       0

We can create additional columns to this view by using following sentence:

In [14]:
gold_sw["diff"] = gold_sw["Gold"] - gold_sw["Gold.1"]
gold_sw.head()

C:\Users\javier.santos\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

             Gold  Gold.1  diff
Afghanistan     0       0     0
Algeria         5       0     5
Argentina      18       0    18
Armenia         1       0     1
Australasia     3       0     3

In [15]:
gold_sw = gold_sw.loc[:,"Gold"] - gold_sw.loc[:,"Gold.1"]
gold_sw.head()

Afghanistan     0
Algeria         5
Argentina      18
Armenia         1
Australasia     3
dtype: int64

In [16]:
print(gold_sw.argmax())

United States

In [17]:
print(gold_sw.loc["United States"])

# Verify whether the values are correct
print(df.loc["United States"])
print(df.loc["United States","Gold"])
print(df.loc["United States","Gold.1"])

880
# Summer            26
Gold               976
Silver             757
Bronze             666
Total             2399
# Winter            22
Gold.1              96
Silver.1           102
Bronze.1            84
Total.1            282
# Games             48
Gold.2            1072
Silver.2           859
Bronze.2           750
Combined total    2681
ID                 USA
Name: United States, dtype: object
976
96

Since the counter are correct we can now rewrite the final answer

### Answer Question 2

In [18]:
def answer_two():
    return (df.loc[:,"Gold"] - df.loc[:,"Gold.1"]).argmax()
answer_two()

'United States'

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

First we can how can we get the total of a column.

In [19]:
df["Gold"].sum()

4809

In [20]:
print("*****Substract golds medals: Summer - Winter******")
num = df.loc[:,"Gold"] - df.loc[:,"Gold.1"]
print(num.head())
print("****Sorten values******")
df_order = df.sort_values(["Gold"],axis=0, ascending=False)
print(df_order.head())
print(df_order.tail())
print("****Total Gold******")
den = df.loc[:,"Gold"] + df.loc[:,"Gold.1"]
print(den.loc["United States"])
print(den.loc["Great Britain"])
print("***TOTAL SUM")
print(den.sum())

*****Substract golds medals: Summer - Winter******
Afghanistan     0
Algeria         5
Argentina      18
Armenia         1
Australasia     3
dtype: int64
****Sorten values******
               # Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
United States        26   976     757     666   2399        22      96
Soviet Union          9   395     319     296   1010         9      78
Great Britain        27   236     272     272    780        22      10
France               27   202     223     246    671        22      31
China                 9   201     146     126    473        10      12

               Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  \
United States       102        84      282       48    1072       859
Soviet Union         57        59      194       18     473       376
Great Britain         4        12       26       49     246       276
France               31        47      109       49     233       254
China                22        19       53       19     213       168

               Bronze.2  Combined total   ID
United States       750            2681  USA
Soviet Union        355            1204  URS
Great Britain       284             806  GBR
France              293             780  FRA
China               145             526  CHN
             # Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Djibouti            7     0       0       1      1         0       0
Cyprus              9     0       1       0      1        10       0
Kyrgyzstan          5     0       1       2      3         6       0
Senegal            13     0       1       0      1         5       0
Afghanistan        13     0       0       2      2         0       0

             Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  Bronze.2  \
Djibouti            0         0        0        7       0         0         1
Cyprus              0         0        0       19       0         1         0
Kyrgyzstan          0         0        0       11       0         1         2
Senegal             0         0        0       18       0         1         0
Afghanistan         0         0        0       13       0         0         2

             Combined total   ID
Djibouti                  1  DJI
Cyprus                    1  CYP
Kyrgyzstan                3  KGZ
Senegal                   1  SEN
Afghanistan               2  AFG
****Total Gold******
1072
246
***TOTAL SUM
5768

In [21]:
print("****Total Gold (No compute)******")
print(df["Gold.2"].sum())
print("****Total Gold (No compute)******")
op = num/df["Gold.2"].sum()
print(op)
print("*** SOLUTION ***")
print(op.argmax())

****Total Gold (No compute)******
5768
****Total Gold (No compute)******
Afghanistan                         0.000000
Algeria                             0.000867
Argentina                           0.003121
Armenia                             0.000173
Australasia                         0.000520
Australia                           0.023232
Austria                            -0.007108
Azerbaijan                          0.001040
Bahamas                             0.000867
Bahrain                             0.000000
Barbados                            0.000000
Belarus                             0.001040
Belgium                             0.006241
Bermuda                             0.000000
Bohemia                             0.000000
Botswana                            0.000000
Brazil                              0.003988
British West Indies                 0.000000
Bulgaria                            0.008669
Burundi                             0.000173
Cameroon                            0.000520
Canada                             -0.000520
Chile                               0.000347
China                               0.032767
Colombia                            0.000347
Costa Rica                          0.000173
Ivory Coast                         0.000000
Croatia                             0.000347
Cuba                                0.012483
Cyprus                              0.000000
                                      ...
Spain                               0.006241
Sri Lanka                           0.000000
Sudan                               0.000000
Suriname                            0.000173
Sweden                              0.016123
Switzerland                        -0.000520
Syria                               0.000173
Chinese Taipei                      0.000347
Tajikistan                          0.000000
Tanzania                            0.000000
Thailand                            0.001214
Togo                                0.000000
Tonga                               0.000000
Trinidad and Tobago                 0.000347
Tunisia                             0.000520
Turkey                              0.006761
Uganda                              0.000347
Ukraine                             0.005374
United Arab Emirates                0.000173
United States                       0.152566
Uruguay                             0.000347
Uzbekistan                          0.000693
Venezuela                           0.000347
Vietnam                             0.000000
Virgin Islands                      0.000000
Yugoslavia                          0.004508
Independent Olympic Participants    0.000000
Zambia                              0.000000
Zimbabwe                            0.000520
Mixed team                          0.001387
dtype: float64
*** SOLUTION ***
United States

### Answer Question 3

In [219]:
def answer_three():
    return ((df.loc[:,"Gold"] - df.loc[:,"Gold.1"])/df["Gold.2"].sum()).argmax()
answer_three()

'United States'

In [225]:
df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,AFG
Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,ALG
Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,ARG
Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,ARM
Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,ANZ

In [230]:
filter = df[(df["Gold"]>0) & (df["Gold.1"]>0)]
filter.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Australia,25,139,152,177,468,18,5,3,4,12,43,144,155,181,480,AUS
Austria,26,18,33,35,86,22,59,78,81,218,48,77,111,116,304,AUT
Belarus,5,12,24,39,75,6,6,4,5,15,11,18,28,44,90,BLR
Belgium,25,37,52,53,142,20,1,1,3,5,45,38,53,56,147,BEL
Bulgaria,19,51,85,78,214,19,1,2,3,6,38,52,87,81,220,BUL

Seems I left the sum function at the end. Since I am using the total value, no sum need to be computed

In [229]:
def answer_three():
    filter = df[(df["Gold"]>0) & (df["Gold.1"]>0)]
    return ((filter.loc[:,"Gold"] - filter.loc[:,"Gold.1"])/filter["Gold.2"]).argmax()
answer_three()

'Bulgaria'

In [218]:
new_loc = (df.loc[:,"Gold"] - df.loc[:,"Gold.1"])/df["Gold.2"]
new_loc

Afghanistan                              NaN
Algeria                             1.000000
Argentina                           1.000000
Armenia                             1.000000
Australasia                         1.000000
Australia                           0.930556
Austria                            -0.532468
Azerbaijan                          1.000000
Bahamas                             1.000000
Bahrain                                  NaN
Barbados                                 NaN
Belarus                             0.333333
Belgium                             0.947368
Bermuda                                  NaN
Bohemia                                  NaN
Botswana                                 NaN
Brazil                              1.000000
British West Indies                      NaN
Bulgaria                            0.961538
Burundi                             1.000000
Cameroon                            1.000000
Canada                             -0.024793
Chile                               1.000000
China                               0.887324
Colombia                            1.000000
Costa Rica                          1.000000
Ivory Coast                              NaN
Croatia                             0.200000
Cuba                                1.000000
Cyprus                                   NaN
                                      ...
Spain                               0.947368
Sri Lanka                                NaN
Sudan                                    NaN
Suriname                            1.000000
Sweden                              0.481865
Switzerland                        -0.030928
Syria                               1.000000
Chinese Taipei                      1.000000
Tajikistan                               NaN
Tanzania                                 NaN
Thailand                            1.000000
Togo                                     NaN
Tonga                                    NaN
Trinidad and Tobago                 1.000000
Tunisia                             1.000000
Turkey                              1.000000
Uganda                              1.000000
Ukraine                             0.885714
United Arab Emirates                1.000000
United States                       0.820896
Uruguay                             1.000000
Uzbekistan                          0.666667
Venezuela                           1.000000
Vietnam                                  NaN
Virgin Islands                           NaN
Yugoslavia                          1.000000
Independent Olympic Participants         NaN
Zambia                                   NaN
Zimbabwe                            1.000000
Mixed team                          1.000000
dtype: float64

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created.

*This function should return a Series named `Points` of length 146*

In [23]:
print(df.count())
print(type(df))
print(type(df["Gold"]))
print(type(df[["Gold","Gold.1"]]))
print(type(df.loc[:,["Gold","Gold.1"]]))

# Summer          146
Gold              146
Silver            146
Bronze            146
Total             146
# Winter          146
Gold.1            146
Silver.1          146
Bronze.1          146
Total.1           146
# Games           146
Gold.2            146
Silver.2          146
Bronze.2          146
Combined total    146
ID                146
dtype: int64
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

Indexing a single column it will return a Series, however selecting multiple columns will return a dataframe

In [24]:
df.loc[:,["Gold.2","Silver.2","Bronze.2"]].head()

             Gold.2  Silver.2  Bronze.2
Afghanistan       0         0         2
Algeria           5         2         8
Argentina        18        24        28
Armenia           1         2         9
Australasia       3         4         5

In [25]:
new_df = (df["Gold.2"] * 3) + (df["Silver.2"]) * 2 + (df["Bronze.2"] * 1)
new_df.head()

Afghanistan      2
Algeria         27
Argentina      130
Armenia         16
Australasia     22
dtype: int64

In [26]:
print(type(new_df))
(18*3)+(24*2)+(28)

<class 'pandas.core.series.Series'>

130

In [27]:
new_df.rename("Points")

Afghanistan                            2
Algeria                               27
Argentina                            130
Armenia                               16
Australasia                           22
Australia                            923
Austria                              569
Azerbaijan                            43
Bahamas                               24
Bahrain                                1
Barbados                               1
Belarus                              154
Belgium                              276
Bermuda                                1
Bohemia                                5
Botswana                               2
Brazil                               184
British West Indies                    2
Bulgaria                             411
Burundi                                3
Cameroon                              12
Canada                               846
Chile                                 24
China                               1120
Colombia                              29
Costa Rica                             7
Ivory Coast                            2
Croatia                               67
Cuba                                 420
Cyprus                                 2
                                    ...
Spain                                268
Sri Lanka                              4
Sudan                                  2
Suriname                               4
Sweden                              1217
Switzerland                          630
Syria                                  6
Chinese Taipei                        32
Tajikistan                             4
Tanzania                               4
Thailand                              44
Togo                                   1
Tonga                                  2
Trinidad and Tobago                   27
Tunisia                               19
Turkey                               191
Uganda                                14
Ukraine                              220
United Arab Emirates                   3
United States                       5684
Uruguay                               16
Uzbekistan                            38
Venezuela                             18
Vietnam                                4
Virgin Islands                         2
Yugoslavia                           171
Independent Olympic Participants       4
Zambia                                 3
Zimbabwe                              18
Mixed team                            38
Name: Points, dtype: int64

In [28]:
my_serie = pd.Series(new_df,name="Points")

In [29]:
my_serie.head()

Afghanistan      2
Algeria         27
Argentina      130
Armenia         16
Australasia     22
Name: Points, dtype: int64

### Answer Question 5

In [30]:
def answer_four():
    return pd.Series((df["Gold.2"] * 3) + (df["Silver.2"]) * 2 + df["Bronze.2"],name="Points")

In [31]:
answer_four().head()

Afghanistan      2
Algeria         27
Argentina      130
Armenia         16
Australasia     22
Name: Points, dtype: int64

### Part 2

For the next set of questions, we will be using census data from the United States Census Bureau. Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. See this document for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5

Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

This function should return a single string value.

In [32]:
census_df = pd.read_csv('census.csv')
census_df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [33]:
print(census_df["STNAME"].unique())

['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'District of Columbia' 'Florida' 'Georgia'
 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas' 'Kentucky'
 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan' 'Minnesota'
 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada' 'New Hampshire'
 'New Jersey' 'New Mexico' 'New York' 'North Carolina' 'North Dakota'
 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Rhode Island' 'South Carolina'
 'South Dakota' 'Tennessee' 'Texas' 'Utah' 'Vermont' 'Virginia'
 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming']

In [34]:
# Get the unique values for the state


filter = census_df["STNAME"] == "Alabama"
alabama_counties = census_df[filter]
print(alabama_counties.count())
print(alabama_counties.head())

SUMLEV                   68
REGION                   68
DIVISION                 68
STATE                    68
COUNTY                   68
STNAME                   68
CTYNAME                  68
CENSUS2010POP            68
ESTIMATESBASE2010        68
POPESTIMATE2010          68
POPESTIMATE2011          68
POPESTIMATE2012          68
POPESTIMATE2013          68
POPESTIMATE2014          68
POPESTIMATE2015          68
NPOPCHG_2010             68
NPOPCHG_2011             68
NPOPCHG_2012             68
NPOPCHG_2013             68
NPOPCHG_2014             68
NPOPCHG_2015             68
BIRTHS2010               68
BIRTHS2011               68
BIRTHS2012               68
BIRTHS2013               68
BIRTHS2014               68
BIRTHS2015               68
DEATHS2010               68
DEATHS2011               68
DEATHS2012               68
                         ..
RBIRTH2011               68
RBIRTH2012               68
RBIRTH2013               68
RBIRTH2014               68
RBIRTH2015               68
RDEATH2011               68
RDEATH2012               68
RDEATH2013               68
RDEATH2014               68
RDEATH2015               68
RNATURALINC2011          68
RNATURALINC2012          68
RNATURALINC2013          68
RNATURALINC2014          68
RNATURALINC2015          68
RINTERNATIONALMIG2011    68
RINTERNATIONALMIG2012    68
RINTERNATIONALMIG2013    68
RINTERNATIONALMIG2014    68
RINTERNATIONALMIG2015    68
RDOMESTICMIG2011         68
RDOMESTICMIG2012         68
RDOMESTICMIG2013         68
RDOMESTICMIG2014         68
RDOMESTICMIG2015         68
RNETMIG2011              68
RNETMIG2012              68
RNETMIG2013              68
RNETMIG2014              68
RNETMIG2015              68
dtype: int64
   SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
0      40       3         6      1       0  Alabama         Alabama
1      50       3         6      1       1  Alabama  Autauga County
2      50       3         6      1       3  Alabama  Baldwin County
3      50       3         6      1       5  Alabama  Barbour County
4      50       3         6      1       7  Alabama     Bibb County

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010     ...       \
0        4779736            4780127          4785161     ...
1          54571              54571            54660     ...
2         182265             182265           183193     ...
3          27457              27457            27341     ...
4          22915              22919            22861     ...

   RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
0          0.002295         -0.193196          0.381066          0.582002
1          7.242091         -2.915927         -3.012349          2.265971
2         14.832960         17.647293         21.845705         19.243287
3         -4.728132         -2.500690         -7.056824         -3.904217
4         -5.527043         -5.068871         -6.201001         -0.177537

   RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
0         -0.467369     1.030015     0.826644     1.383282     1.724718
1         -2.530799     7.606016    -2.626146    -2.722002     2.592270
2         17.197872    15.844176    18.559627    22.727626    20.317142
3        -10.543299    -4.874741    -2.758113    -7.167664    -3.978583
4          0.177258    -5.088389    -4.363636    -5.403729     0.754533

   RNETMIG2015
0     0.712594
1    -2.187333
2    18.293499
3   -10.543299
4     1.107861

[5 rows x 100 columns]

In [35]:
census_df["STNAME"].value_counts()

Texas                   255
Georgia                 160
Virginia                134
Kentucky                121
Missouri                116
Kansas                  106
Illinois                103
North Carolina          101
Iowa                    100
Tennessee                96
Nebraska                 94
Indiana                  93
Ohio                     89
Minnesota                88
Michigan                 84
Mississippi              83
Oklahoma                 78
Arkansas                 76
Wisconsin                73
Pennsylvania             68
Alabama                  68
Florida                  68
South Dakota             67
Colorado                 65
Louisiana                65
New York                 63
California               59
Montana                  57
West Virginia            56
North Dakota             54
South Carolina           47
Idaho                    45
Washington               40
Oregon                   37
New Mexico               34
Alaska                   30
Utah                     30
Maryland                 25
Wyoming                  24
New Jersey               22
Nevada                   18
Maine                    17
Arizona                  16
Massachusetts            15
Vermont                  15
New Hampshire            11
Connecticut               9
Rhode Island              6
Hawaii                    6
Delaware                  4
District of Columbia      2
Name: STNAME, dtype: int64

In [36]:
census_df["STNAME"].value_counts().argmax()

'Texas'

In [37]:
census_df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [38]:
census_df_mod = census_df[census_df["SUMLEV"] != 40]
census_df_mod.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411

In [39]:
print(census_df.count())
print(census_df_mod.count())

SUMLEV                   3193
REGION                   3193
DIVISION                 3193
STATE                    3193
COUNTY                   3193
STNAME                   3193
CTYNAME                  3193
CENSUS2010POP            3193
ESTIMATESBASE2010        3193
POPESTIMATE2010          3193
POPESTIMATE2011          3193
POPESTIMATE2012          3193
POPESTIMATE2013          3193
POPESTIMATE2014          3193
POPESTIMATE2015          3193
NPOPCHG_2010             3193
NPOPCHG_2011             3193
NPOPCHG_2012             3193
NPOPCHG_2013             3193
NPOPCHG_2014             3193
NPOPCHG_2015             3193
BIRTHS2010               3193
BIRTHS2011               3193
BIRTHS2012               3193
BIRTHS2013               3193
BIRTHS2014               3193
BIRTHS2015               3193
DEATHS2010               3193
DEATHS2011               3193
DEATHS2012               3193
                         ...
RBIRTH2011               3193
RBIRTH2012               3193
RBIRTH2013               3193
RBIRTH2014               3193
RBIRTH2015               3193
RDEATH2011               3193
RDEATH2012               3193
RDEATH2013               3193
RDEATH2014               3193
RDEATH2015               3193
RNATURALINC2011          3193
RNATURALINC2012          3193
RNATURALINC2013          3193
RNATURALINC2014          3193
RNATURALINC2015          3193
RINTERNATIONALMIG2011    3193
RINTERNATIONALMIG2012    3193
RINTERNATIONALMIG2013    3193
RINTERNATIONALMIG2014    3193
RINTERNATIONALMIG2015    3193
RDOMESTICMIG2011         3193
RDOMESTICMIG2012         3193
RDOMESTICMIG2013         3193
RDOMESTICMIG2014         3193
RDOMESTICMIG2015         3193
RNETMIG2011              3193
RNETMIG2012              3193
RNETMIG2013              3193
RNETMIG2014              3193
RNETMIG2015              3193
dtype: int64
SUMLEV                   3142
REGION                   3142
DIVISION                 3142
STATE                    3142
COUNTY                   3142
STNAME                   3142
CTYNAME                  3142
CENSUS2010POP            3142
ESTIMATESBASE2010        3142
POPESTIMATE2010          3142
POPESTIMATE2011          3142
POPESTIMATE2012          3142
POPESTIMATE2013          3142
POPESTIMATE2014          3142
POPESTIMATE2015          3142
NPOPCHG_2010             3142
NPOPCHG_2011             3142
NPOPCHG_2012             3142
NPOPCHG_2013             3142
NPOPCHG_2014             3142
NPOPCHG_2015             3142
BIRTHS2010               3142
BIRTHS2011               3142
BIRTHS2012               3142
BIRTHS2013               3142
BIRTHS2014               3142
BIRTHS2015               3142
DEATHS2010               3142
DEATHS2011               3142
DEATHS2012               3142
                         ...
RBIRTH2011               3142
RBIRTH2012               3142
RBIRTH2013               3142
RBIRTH2014               3142
RBIRTH2015               3142
RDEATH2011               3142
RDEATH2012               3142
RDEATH2013               3142
RDEATH2014               3142
RDEATH2015               3142
RNATURALINC2011          3142
RNATURALINC2012          3142
RNATURALINC2013          3142
RNATURALINC2014          3142
RNATURALINC2015          3142
RINTERNATIONALMIG2011    3142
RINTERNATIONALMIG2012    3142
RINTERNATIONALMIG2013    3142
RINTERNATIONALMIG2014    3142
RINTERNATIONALMIG2015    3142
RDOMESTICMIG2011         3142
RDOMESTICMIG2012         3142
RDOMESTICMIG2013         3142
RDOMESTICMIG2014         3142
RDOMESTICMIG2015         3142
RNETMIG2011              3142
RNETMIG2012              3142
RNETMIG2013              3142
RNETMIG2014              3142
RNETMIG2015              3142
dtype: int64

In [40]:
result = census_df[census_df["SUMLEV"] != 40]["STNAME"].value_counts().argmax()
print(result)

Texas

### Answer Question 5

In [41]:
def answer_five():
    return census_df[census_df["SUMLEV"] != 40]["STNAME"].value_counts().argmax()
answer_five()

'Texas'

### Question 6

Only looking at the three most populous counties for each state, what are the three most populous states (in order of highest population to lowest population)? Use CENSUS2010POP.

This function should return a list of string values.

In [42]:
sort_list = census_df.sort_values(by="CENSUS2010POP", ascending=False)
sort_list.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
190,40,4,9,6,0,California,California,37253956,37254503,37334079,...,-1.148464,-1.163788,-1.339869,-0.862856,-1.981572,2.761704,2.647127,2.728645,3.743342,2.656065
2566,40,3,7,48,0,Texas,Texas,25145561,25146105,25244363,...,4.527491,5.484904,4.446476,6.072953,6.248252,7.616364,8.660719,7.739851,9.780487,9.978697
1860,40,1,2,36,0,New York,New York,19378102,19378087,19402920,...,-4.354557,-5.945385,-5.561401,-8.130297,-7.990563,1.439239,-0.402860,0.407960,-1.334639,-1.205321
329,40,3,5,12,0,Florida,Florida,18801310,18804623,18849890,...,5.556307,5.138184,4.847420,6.958576,10.080932,11.364173,10.676030,10.565882,13.478570,16.528676
608,40,2,3,17,0,Illinois,Illinois,12830632,12831549,12841249,...,-5.243330,-5.805172,-5.308960,-7.509147,-8.174675,-3.020410,-3.519051,-2.830379,-4.625216,-5.247030

In [43]:
normalized_census =census_df[census_df["SUMLEV"] != 40]
three_countries = normalized_census.groupby('STNAME').head(3)
three_countries.head(20)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
69,50,4,9,2,13,Alaska,Aleutians East Borough,3141,3141,3169,...,-5.604858,-12.221204,-17.257039,-27.748454,-16.221087,19.305620,8.249313,5.752346,-3.920977,7.509763
70,50,4,9,2,16,Alaska,Aleutians West Census Area,5561,5561,5546,...,-11.496318,0.000000,-13.711875,-11.179039,-26.717891,1.257410,13.314397,0.175793,4.890830,-10.826858
71,50,4,9,2,20,Alaska,Anchorage Municipality,291826,291826,293405,...,-3.788123,-7.563712,-3.962343,-18.897015,-19.781254,-0.969922,-2.652342,0.053320,-14.789980,-15.280810
99,50,4,8,4,1,Arizona,Apache County,71518,71518,71766,...,1.775891,1.197250,-20.566049,-5.674114,-11.302431,2.094996,1.500003,-20.220982,-5.326435,-10.939637
100,50,4,8,4,3,Arizona,Cochise County,131346,131357,131809,...,3.353411,-15.621933,-22.883978,-23.290753,-13.596166,5.128302,-12.065659,-20.574165,-20.939882,-10.798115
101,50,4,8,4,5,Arizona,Coconino County,134421,134437,134626,...,-12.402905,4.908203,-3.154921,-0.809483,2.992043,-11.569596,5.818774,-2.120401,0.444851,4.256795
115,50,3,7,5,1,Arkansas,Arkansas County,19019,19018,19014,...,-6.544054,2.799271,-10.483124,-15.687324,-7.460064,-5.488561,3.802783,-9.424222,-14.455896,-6.216720
116,50,3,7,5,3,Arkansas,Ashley County,21853,21853,21831,...,-8.785244,-9.410783,-11.842074,-14.846789,-4.453596,-8.831241,-9.457142,-11.888881,-14.846789,-4.453596
117,50,3,7,5,5,Arkansas,Baxter County,41513,41513,41538,...,2.101170,3.230547,4.851824,5.280722,10.696624,2.125322,3.279127,4.900586,5.329617,10.745467
191,50,4,9,6,1,California,Alameda County,1510271,1510261,1513754,...,-0.363660,2.488670,3.743636,4.436457,2.141452,6.535369,9.157917,10.954544,12.487898,10.059473
192,50,4,9,6,3,California,Alpine County,1175,1175,1159,...,-47.577093,11.622709,15.859031,-32.874278,6.314840,-46.696035,12.516764,16.740088,-31.985784,7.216960
193,50,4,9,6,5,California,Amador County,38091,38091,37873,...,-3.766029,-8.440854,-9.743520,7.254381,10.034579,-3.527337,-8.065705,-9.254987,7.772551,10.549868
250,50,4,8,8,1,Colorado,Adams County,441603,441687,443680,...,5.982917,7.689510,9.494072,10.849385,10.003023,7.605895,9.334759,11.312999,12.975974,12.150054
251,50,4,8,8,3,Colorado,Alamosa County,15445,15445,15926,...,5.490906,-5.517156,2.592433,-5.340044,1.706589,6.114872,-4.711279,3.580026,-4.296587,2.742732
252,50,4,8,8,5,Colorado,Arapahoe County,572003,572155,574727,...,7.756987,6.256681,8.577457,6.718039,7.128637,11.252972,10.087820,12.627969,11.245590,11.633206
315,50,1,1,9,1,Connecticut,Fairfield County,916829,916850,919744,...,-0.228261,-3.030708,-2.070291,-6.633789,-7.385939,6.119788,2.687406,4.096896,0.441829,-0.338989
316,50,1,1,9,3,Connecticut,Hartford County,894014,894029,895303,...,-5.037297,-6.324143,-5.237664,-8.636074,-8.135161,-0.025666,-1.662136,-0.314193,-2.840433,-2.327200

In [44]:
census_df[census_df["SUMLEV"] == 40]["CENSUS2010POP"].head(10)

0       4779736
68       710231
98      6392017
114     2915918
190    37253956
249     5029196
314     3574097
323      897934
327      601723
329    18801310
Name: CENSUS2010POP, dtype: int64

In [45]:
print(census_df.iloc[0])
print(census_df.iloc[68])

print(census_df.iloc[98])

SUMLEV                           40
REGION                            3
DIVISION                          6
STATE                             1
COUNTY                            0
STNAME                      Alabama
CTYNAME                     Alabama
CENSUS2010POP               4779736
ESTIMATESBASE2010           4780127
POPESTIMATE2010             4785161
POPESTIMATE2011             4801108
POPESTIMATE2012             4816089
POPESTIMATE2013             4830533
POPESTIMATE2014             4846411
POPESTIMATE2015             4858979
NPOPCHG_2010                   5034
NPOPCHG_2011                  15947
NPOPCHG_2012                  14981
NPOPCHG_2013                  14444
NPOPCHG_2014                  15878
NPOPCHG_2015                  12568
BIRTHS2010                    14226
BIRTHS2011                    59689
BIRTHS2012                    59062
BIRTHS2013                    57938
BIRTHS2014                    58334
BIRTHS2015                    58305
DEATHS2010                    11089
DEATHS2011                    48811
DEATHS2012                    48357
                            ...
RBIRTH2011                   12.453
RBIRTH2012                  12.2826
RBIRTH2013                  12.0121
RBIRTH2014                  12.0563
RBIRTH2015                   12.015
RDEATH2011                  10.1835
RDEATH2012                  10.0564
RDEATH2013                  10.5411
RDEATH2014                   10.381
RDEATH2015                  10.3716
RNATURALINC2011              2.2695
RNATURALINC2012             2.22622
RNATURALINC2013             1.47098
RNATURALINC2014             1.67532
RNATURALINC2015             1.64342
RINTERNATIONALMIG2011       1.02772
RINTERNATIONALMIG2012       1.01984
RINTERNATIONALMIG2013       1.00222
RINTERNATIONALMIG2014       1.14272
RINTERNATIONALMIG2015       1.17996
RDOMESTICMIG2011         0.00229495
RDOMESTICMIG2012          -0.193196
RDOMESTICMIG2013           0.381066
RDOMESTICMIG2014           0.582002
RDOMESTICMIG2015          -0.467369
RNETMIG2011                 1.03001
RNETMIG2012                0.826644
RNETMIG2013                 1.38328
RNETMIG2014                 1.72472
RNETMIG2015                0.712594
Name: 0, dtype: object
SUMLEV                         40
REGION                          4
DIVISION                        9
STATE                           2
COUNTY                          0
STNAME                     Alaska
CTYNAME                    Alaska
CENSUS2010POP              710231
ESTIMATESBASE2010          710249
POPESTIMATE2010            714021
POPESTIMATE2011            722720
POPESTIMATE2012            731228
POPESTIMATE2013            737442
POPESTIMATE2014            737046
POPESTIMATE2015            738432
NPOPCHG_2010                 3772
NPOPCHG_2011                 8699
NPOPCHG_2012                 8508
NPOPCHG_2013                 6214
NPOPCHG_2014                 -396
NPOPCHG_2015                 1386
BIRTHS2010                   2892
BIRTHS2011                  11711
BIRTHS2012                  11126
BIRTHS2013                  11348
BIRTHS2014                  11462
BIRTHS2015                  11498
DEATHS2010                    918
DEATHS2011                   3928
DEATHS2012                   3934
                           ...
RBIRTH2011                16.3022
RBIRTH2012                15.3045
RBIRTH2013                15.4534
RBIRTH2014                15.5471
RBIRTH2015                15.5855
RDEATH2011                5.46793
RDEATH2012                5.41147
RDEATH2013                5.50158
RDEATH2014                5.65891
RDEATH2015                5.80422
RNATURALINC2011           10.8342
RNATURALINC2012           9.89306
RNATURALINC2013           9.95186
RNATURALINC2014           9.88818
RNATURALINC2015           9.78124
RINTERNATIONALMIG2011     2.10476
RINTERNATIONALMIG2012     3.76492
RINTERNATIONALMIG2013     3.15796
RINTERNATIONALMIG2014      3.1672
RINTERNATIONALMIG2015     3.52564
RDOMESTICMIG2011         -1.17349
RDOMESTICMIG2012         -1.94642
RDOMESTICMIG2013         -3.91511
RDOMESTICMIG2014         -14.4389
RDOMESTICMIG2015         -10.4075
RNETMIG2011              0.931274
RNETMIG2012                1.8185
RNETMIG2013             -0.757148
RNETMIG2014              -11.2717
RNETMIG2015              -6.88184
Name: 68, dtype: object
SUMLEV                        40
REGION                         4
DIVISION                       8
STATE                          4
COUNTY                         0
STNAME                   Arizona
CTYNAME                  Arizona
CENSUS2010POP            6392017
ESTIMATESBASE2010        6392307
POPESTIMATE2010          6408208
POPESTIMATE2011          6468732
POPESTIMATE2012          6553262
POPESTIMATE2013          6630799
POPESTIMATE2014          6728783
POPESTIMATE2015          6828065
NPOPCHG_2010               15901
NPOPCHG_2011               60524
NPOPCHG_2012               84530
NPOPCHG_2013               77537
NPOPCHG_2014               97984
NPOPCHG_2015               99282
BIRTHS2010                 20937
BIRTHS2011                 86104
BIRTHS2012                 85566
BIRTHS2013                 86103
BIRTHS2014                 86556
BIRTHS2015                 87385
DEATHS2010                 11489
DEATHS2011                 48152
DEATHS2012                 48759
                          ...
RBIRTH2011               13.3734
RBIRTH2012               13.1418
RBIRTH2013               13.0617
RBIRTH2014               12.9579
RBIRTH2015               12.8916
RDEATH2011                7.4788
RDEATH2012               7.48871
RDEATH2013               7.67472
RDEATH2014               7.80683
RDEATH2015                7.8533
RNATURALINC2011          5.89457
RNATURALINC2012          5.65305
RNATURALINC2013          5.38696
RNATURALINC2014          5.15106
RNATURALINC2015          5.03834
RINTERNATIONALMIG2011    1.96289
RINTERNATIONALMIG2012    2.09154
RINTERNATIONALMIG2013    2.21813
RINTERNATIONALMIG2014     2.5414
RINTERNATIONALMIG2015    2.55871
RDOMESTICMIG2011         1.32749
RDOMESTICMIG2012         5.24574
RDOMESTICMIG2013         3.90547
RDOMESTICMIG2014         6.21996
RDOMESTICMIG2015          6.7765
RNETMIG2011              3.29038
RNETMIG2012              7.33728
RNETMIG2013              6.12361
RNETMIG2014              8.76135
RNETMIG2015              9.33521
Name: 98, dtype: object

First, I have to return the first three states ordered by CENSUS2010POP

In [46]:
census_df[census_df["SUMLEV"] == 40].sort_values(by="CENSUS2010POP", ascending=False)["CENSUS2010POP"].head(10)

190     37253956
2566    25145561
1860    19378102
329     18801310
608     12830632
2282    12702379
2078    11536504
1253     9883640
397      9687653
1923     9535483
Name: CENSUS2010POP, dtype: int64

In [47]:
type(census_df[census_df["SUMLEV"] == 40].sort_values(by="CENSUS2010POP", ascending=False))

pandas.core.frame.DataFrame

In [48]:
test = census_df[census_df["SUMLEV"] == 40].sort_values(by="CENSUS2010POP", ascending=False)
test.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
190,40,4,9,6,0,California,California,37253956,37254503,37334079,...,-1.148464,-1.163788,-1.339869,-0.862856,-1.981572,2.761704,2.647127,2.728645,3.743342,2.656065
2566,40,3,7,48,0,Texas,Texas,25145561,25146105,25244363,...,4.527491,5.484904,4.446476,6.072953,6.248252,7.616364,8.660719,7.739851,9.780487,9.978697
1860,40,1,2,36,0,New York,New York,19378102,19378087,19402920,...,-4.354557,-5.945385,-5.561401,-8.130297,-7.990563,1.439239,-0.402860,0.407960,-1.334639,-1.205321
329,40,3,5,12,0,Florida,Florida,18801310,18804623,18849890,...,5.556307,5.138184,4.847420,6.958576,10.080932,11.364173,10.676030,10.565882,13.478570,16.528676
608,40,2,3,17,0,Illinois,Illinois,12830632,12831549,12841249,...,-5.243330,-5.805172,-5.308960,-7.509147,-8.174675,-3.020410,-3.519051,-2.830379,-4.625216,-5.247030

In [49]:
test = test[["STNAME","CENSUS2010POP"]]
test.head()

          STNAME  CENSUS2010POP
190   California       37253956
2566       Texas       25145561
1860    New York       19378102
329      Florida       18801310
608     Illinois       12830632

In [50]:
census_df[census_df["SUMLEV"] == 40].sort_values(by="CENSUS2010POP", ascending=False)[["STNAME","CENSUS2010POP"]].head(3)

          STNAME  CENSUS2010POP
190   California       37253956
2566       Texas       25145561
1860    New York       19378102

Now use these three states to get theirs first three counties with higher census population

In [51]:
# Get the three states with most population
test = census_df[census_df["SUMLEV"] == 40].sort_values(by="CENSUS2010POP", ascending=False)[["STNAME","CENSUS2010POP"]].head(3)
#For each one of these three states let's create a list with the three more desnse counties
# normalized_census =census_df[census_df["SUMLEV"] != 40]
three_countries = census_df[census_df["SUMLEV"] != 40].groupby('STNAME').head(3)

In [52]:
test.head()

          STNAME  CENSUS2010POP
190   California       37253956
2566       Texas       25145561
1860    New York       19378102

In [53]:
three_countries.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
69,50,4,9,2,13,Alaska,Aleutians East Borough,3141,3141,3169,...,-5.604858,-12.221204,-17.257039,-27.748454,-16.221087,19.305620,8.249313,5.752346,-3.920977,7.509763
70,50,4,9,2,16,Alaska,Aleutians West Census Area,5561,5561,5546,...,-11.496318,0.000000,-13.711875,-11.179039,-26.717891,1.257410,13.314397,0.175793,4.890830,-10.826858

In [54]:
list = [three_countries[three_countries["STNAME"] == row["STNAME"]].head(3) for row in test]

TypeError: string indices must be integers

In [ ]:
row = test[test["STNAME"] == "California"]
print(row)

In [ ]:
print(row["STNAME"])

In [ ]:
print(row.get("STNAME").values[0])

In [ ]:
print(row["STNAME"].values[0])

In [ ]:
three_countries["STNAME"].head()

In [ ]:
three_countries[three_countries["STNAME"] == "Alabama"]

In [ ]:
test["STNAME"]

In [ ]:
for row in test.values:
    print(row)

In [ ]:
list = [three_countries[three_countries["STNAME"] == row["STNAME"]].head(3)

Only looking at the three most populous counties for each state, what are the three most populous states (in order of highest population to lowest population)? Use CENSUS2010POP.

This function should return a list of string values.

In [55]:
test

          STNAME  CENSUS2010POP
190   California       37253956
2566       Texas       25145561
1860    New York       19378102

In [61]:
type(test.iloc[0])

pandas.core.series.Series

In [65]:
for row in test.values:
    print(row[0])

California
Texas
New York

In [71]:
list = [three_countries[three_countries["STNAME"] == row[0]].head(3) for row in test]

In [81]:
list = three_countries[three_countries.sort_values(by="CENSUS2010POP", ascending=False)["STNAME"] == "California"].head(3)
type(list)

pandas.core.frame.DataFrame

In [82]:
list.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
209,50,4,9,6,37,California,Los Angeles County,9818605,9818700,9826009,...,-4.999439,-4.071266,-4.332318,-5.394299,-6.027694,-0.007808,0.377510,0.578049,0.215038,-0.437481
227,50,4,9,6,73,California,San Diego County,3095313,3095308,3104386,...,0.354751,0.235513,-0.246567,0.657077,-2.855045,4.382515,5.773072,4.745940,5.921091,2.770965
220,50,4,9,6,59,California,Orange County,3010232,3010266,3017866,...,1.992772,0.618346,-0.491825,-2.374727,-3.182714,6.033306,4.395138,3.681764,2.407607,1.587398

In [78]:
three_countries = census_df[census_df["SUMLEV"] != 40].sort_values(by="CENSUS2010POP", ascending=False).groupby('STNAME').head(3)

In [83]:
three_countries

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
209,50,4,9,6,37,California,Los Angeles County,9818605,9818700,9826009,...,-4.999439,-4.071266,-4.332318,-5.394299,-6.027694,-0.007808,0.377510,0.578049,0.215038,-0.437481
624,50,2,3,17,31,Illinois,Cook County,5194675,5195022,5199303,...,-6.399085,-5.939523,-6.011973,-9.374552,-10.561919,-3.000501,-2.669330,-2.358718,-5.102980,-6.263994
2667,50,3,7,48,201,Texas,Harris County,4092459,4093076,4108187,...,1.403957,3.518819,4.820913,5.243613,3.794291,7.154417,8.915715,10.683269,11.850629,10.303814
106,50,4,8,4,13,Arizona,Maricopa County,3817117,3817357,3825597,...,2.444413,9.232973,7.879873,8.318210,9.123309,4.726436,11.527593,10.390177,11.203958,11.985998
227,50,4,9,6,73,California,San Diego County,3095313,3095308,3104386,...,0.354751,0.235513,-0.246567,0.657077,-2.855045,4.382515,5.773072,4.745940,5.921091,2.770965
220,50,4,9,6,59,California,Orange County,3010232,3010266,3017866,...,1.992772,0.618346,-0.491825,-2.374727,-3.182714,6.033306,4.395138,3.681764,2.407607,1.587398
1884,50,1,2,36,47,New York,Kings County,2504700,2504710,2510335,...,-6.116225,-7.066189,-8.271203,-12.671578,-12.425023,3.070971,1.380027,0.899094,-2.260948,-2.107864
372,50,3,5,12,86,Florida,Miami-Dade County,2496435,2498017,2508171,...,7.464259,-6.908149,-8.130040,-10.464276,-12.205475,23.110902,6.891198,6.633403,6.087936,4.154777
2623,50,3,7,48,113,Texas,Dallas County,2368139,2367643,2373464,...,0.646423,4.853046,-2.117265,-0.754784,-0.981666,5.233271,9.100284,2.574144,4.639783,4.397784
1901,50,1,2,36,81,New York,Queens County,2230722,2230541,2235573,...,-7.701619,-9.309401,-7.554518,-11.787697,-10.891968,3.748957,1.318590,3.998295,1.244451,2.001030
1777,50,4,8,32,3,Nevada,Clark County,1951269,1951269,1953378,...,-2.799523,6.206036,5.494924,9.848283,11.903114,0.531032,9.344107,8.803899,13.633456,15.680887
3017,50,4,9,53,33,Washington,King County,1931249,1931256,1937699,...,5.141363,5.472471,5.662073,3.337122,2.840873,11.616146,12.013317,12.704538,11.206066,10.589099
1335,50,2,3,26,163,Michigan,Wayne County,1820584,1820641,1815199,...,-13.340073,-10.271616,-14.119617,-11.903253,-8.762835,-11.344758,-8.098421,-11.732437,-9.161648,-6.010195
2786,50,3,7,48,439,Texas,Tarrant County,1809034,1809531,1816528,...,5.092591,6.491618,4.793224,5.070751,6.024164,8.010830,9.415741,7.937773,8.697380,9.639477
335,50,3,5,12,11,Florida,Broward County,1748066,1748148,1753263,...,7.334407,5.473544,1.555403,1.178479,1.072196,15.871353,13.173887,9.767689,10.436646,10.182937
1891,50,1,2,36,61,New York,New York County,1585873,1585874,1588609,...,-2.236119,-5.587580,-10.136168,-13.233013,-9.845545,7.056032,3.454444,-0.280690,-2.021209,1.315259
2333,50,1,2,42,101,Pennsylvania,Philadelphia County,1526006,1526006,1528338,...,-3.941417,-3.595205,-6.773792,-8.654860,-6.799608,1.274033,1.887580,-0.995729,-1.954303,-0.133589
1247,50,1,1,25,17,Massachusetts,Middlesex County,1503085,1503126,1507262,...,-0.022434,-0.289758,-0.129074,-3.275822,-4.215144,7.071195,6.789742,7.459161,5.266357,4.232879
379,50,3,5,12,99,Florida,Palm Beach County,1320134,1320134,1324171,...,4.736597,8.675158,5.992198,8.893634,9.957796,10.665231,14.033170,11.752520,15.407606,16.364047
2096,50,2,3,39,35,Ohio,Cuyahoga County,1280122,1280109,1278226,...,-9.743937,-6.257252,-4.365918,-6.582935,-7.627166,-7.525767,-3.903585,-1.863540,-3.652344,-4.695352
2284,50,1,2,42,3,Pennsylvania,Allegheny County,1223348,1223348,1223933,...,2.227924,0.629637,0.549358,-2.928597,-4.579121,4.361216,3.035926,3.163880,0.038107,-1.619742
1316,50,2,3,26,125,Michigan,Oakland County,1202362,1202362,1202930,...,0.744778,1.714214,2.387837,-1.182556,-5.272740,4.341917,5.554546,6.546585,3.529064,-0.595439
2103,50,2,3,39,49,Ohio,Franklin County,1163414,1163545,1166296,...,0.378458,2.794228,2.332473,3.042470,1.658991,4.186902,6.781175,6.597897,7.825826,6.367244
1364,50,2,4,27,53,Minnesota,Hennepin County,1152425,1152388,1154250,...,1.909896,1.598094,0.900932,-1.313608,-2.862134,6.421691,5.886016,5.526387,3.891067,2.294635
2895,50,3,5,51,59,Virginia,Fairfax County,1081726,1081685,1086835,...,-1.068978,-4.301956,-5.331461,-15.828378,-14.700525,7.703572,4.663819,3.910625,-5.532061,-4.358958
2839,50,4,8,49,35,Utah,Salt Lake County,1029655,1029581,1033182,...,0.521647,1.455453,0.943194,-2.857349,-0.895372,3.354680,4.171416,3.911645,0.519769,2.462501
1604,50,2,4,29,189,Missouri,St. Louis County,998954,998883,998792,...,-3.773135,-2.872300,-3.689182,-3.341181,-3.540176,-1.813988,-0.777081,-1.395556,-0.731726,-0.935404
109,50,4,8,4,19,Arizona,Pima County,980263,980263,981870,...,0.874159,-0.248360,-1.381638,1.036139,0.159859,2.781876,2.000003,0.854104,3.582023,2.777186
1228,50,3,5,24,31,Maryland,Montgomery County,971777,971806,976179,...,0.221404,-2.922672,-4.230770,-6.419664,-7.983224,9.834216,6.138412,5.380039,4.307098,2.649484
559,50,4,9,15,3,Hawaii,Honolulu County,953207,953207,956377,...,-1.214795,-3.988078,-3.313449,-7.336458,-7.509559,4.148817,3.958232,3.848205,0.137451,0.546515
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,50,2,4,19,163,Iowa,Scott County,165224,165224,165744,...,2.776426,4.834859,4.591144,-0.321684,-2.223755,3.593728,5.698226,5.551807,0.795438,-1.123520
324,50,3,5,10,1,Delaware,Kent County,162310,162349,162990,...,6.373541,6.735706,4.991157,7.304533,3.984871,8.195423,9.487672,7.020855,9.368093,6.197402
1442,50,3,6,28,33,Mississippi,DeSoto County,161252,161264,161788,...,6.619487,8.871153,6.427622,9.289057,8.250801,7.184415,9.355585,6.947328,9.949193,8.919000
1069,50,3,6,21,117,Kentucky,Kenton County,159720,159721,160014,...,-2.962446,0.477546,3.375252,-2.937055,-0.978554,-2.139198,1.674512,4.561817,-1.550960,0.401146
1758,50,2,4,31,153,Nebraska,Sarpy County,158840,158840,159755,...,5.440075,5.314389,9.513528,4.114383,7.190006,6.612452,8.711215,11.953047,6.513953,9.931520
2855,50,1,1,50,7,Vermont,Chittenden County,156545,156540,156805,...,-0.044508,-0.031596,0.451860,-1.652769,-3.669383,2.549666,2.932088,3.577223,1.927191,-0.068296
562,50,4,9,15,9,Hawaii,Maui County,154834,154835,154978,...,1.417671,0.450349,4.294788,5.155005,-3.475239,5.734831,4.960182,9.102947,10.544328,1.822976
1206,50,1,1,23,19,Maine,Penobscot County,153923,153920,153871,...,-1.039998,-2.159848,-1.120032,-0.455934,-6.831533,-0.344499,-1.301113,-0.234425,0.501527,-5.845337
2033,50,2,4,38,17,North Dakota,Cass County,149778,149778,150270,...,5.774841,13.778716,20.355710,10.739636,10.661535,9.558811,18.266457,25.059420,15.843083,15.644002
1680,50,4,8,30,111,Montana,Yellowstone County,147972,147972,148406,...,5.243554,8.635373,9.498067,5.664862,4.426873,5.578819,9.059520,9.896816,6.136396,4.881076
1800,50,1,1,33,13,New Hampshire,Merrimack County,146445,146442,146430,...,-0.204651,0.428952,-1.924496,0.386996,1.157537,1.050542,1.525163,-0.768438,1.710928,2.470765
1853,50,4,8,35,49,New Mexico,Santa Fe County,144170,144171,144462,...,1.076393,1.905931,0.872291,0.914848,-1.112373,3.650076,4.257493,3.455091,3.937235,1.968564
591,50,4,8,16,55,Idaho,Kootenai County,138494,138494,138910,...,11.051342,5.498539,11.298725,14.598640,17.641663,11.237079,5.667942,11.549963,14.921073,17.957532
2355,50,1,1,44,9,Rhode Island,Washington County,126979,127094,127085,...,-4.669304,-2.659574,1.551904,1.400112,0.506035,-3.533527,-1.788880,2.462459,2.428442,1.533918
1656,50,4,8,30,63,Montana,Missoula County,109299,109299,109455,...,2.076361,3.444270,1.418261,3.502486,7.308408,3.059900,4.212677,2.315895,4.536299,8.313424
3042,50,3,5,54,3,West Virginia,Berkeley County,104169,104172,104646,...,4.906062,7.784296,8.403712,11.389012,8.385254,5.600137,8.574007,9.127210,12.220127,9.203986
2455,50,2,4,46,103,South Dakota,Pennington County,100948,100937,101300,...,3.975499,11.718108,9.222836,8.486537,-4.240042,4.289613,13.263778,10.104361,9.315627,-3.281424
76,50,4,9,2,90,Alaska,Fairbanks North Star Borough,97581,97581,98289,...,-17.339069,5.430293,-9.147023,-33.436804,-13.859157,-15.791483,10.618791,-4.926084,-29.823633,-8.984834
3046,50,3,5,54,11,West Virginia,Cabell County,96319,96316,96369,...,1.689758,1.002791,0.092837,-3.322773,-2.055031,2.716053,2.243358,1.402865,-1.795536,-0.536993
3180,50,4,8,56,21,Wyoming,Laramie County,91738,91881,92271,...,-1.200428,15.547274,4.787847,-1.226133,0.278940,-0.973320,17.914554,6.003143,-0.207819,1.673640
1639,50,4,8,30,29,Montana,Flathead County,90928,90928,90868,...,-0.428449,1.663020,11.322451,13.841310,10.498138,0.197746,1.838074,11.560819,14.129004,10.791499
85,50,4,9,2,170,Alaska,Matanuska-Susitna Borough,88995,88995,89761,...,13.050517,11.474315,12.906763,15.008086,18.697964,13.391923,12.303913,13.528903,15.605525,19.349985
2032,50,2,4,38,15,North Dakota,Burleigh County,81308,81308,81729,...,12.287856,22.208163,24.006105,14.849577,18.908845,12.554456,22.728482,24.407737,15.274170,19.322987
3182,50,4,8,56,25,Wyoming,Natrona County,75450,75450,75472,...,7.189319,23.066162,24.322042,-0.958472,-0.061057,7.689674,23.749508,25.085233,-0.110593,0.793743
2042,50,2,4,38,35,North Dakota,Grand Forks County,66861,66861,66984,...,-15.370685,2.798535,12.519059,0.286484,-4.150788,-12.093002,7.815059,17.086036,5.099410,0.807491
2862,50,1,1,50,21,Vermont,Rutland County,61642,61646,61585,...,-3.467615,-4.976224,-3.094650,-5.714996,-5.655373,-3.272257,-4.517887,-2.600823,-5.052387,-4.988072
2863,50,1,1,50,23,Vermont,Washington County,59534,59526,59570,...,-1.578161,-5.617505,-3.407759,-4.097008,-6.278073,-1.376694,-5.281128,-3.087227,-3.741482,-5.920784
1792,50,4,8,32,510,Nevada,Carson City,55274,55274,55030,...,-3.716321,-0.676701,-8.816898,7.776150,0.385318,-3.570583,-0.658412,-8.632829,8.034127,0.715590
3172,50,4,8,56,5,Wyoming,Campbell County,46133,46133,46244,...,-2.843479,15.601020,-5.895711,-8.550911,10.916963,-2.649606,15.558684,-5.916543,-8.509402,10.978525
2444,50,2,4,46,83,South Dakota,Lincoln County,44828,44823,45177,...,21.858518,19.072051,19.974142,18.716288,14.429987,22.097765,19.261300,20.177752,18.933231,14.640783

In [84]:
list = three_countries[three_countries["STNAME"] == "California"].head(3)
type(list)

pandas.core.frame.DataFrame

In [86]:
list.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
209,50,4,9,6,37,California,Los Angeles County,9818605,9818700,9826009,...,-4.999439,-4.071266,-4.332318,-5.394299,-6.027694,-0.007808,0.377510,0.578049,0.215038,-0.437481
227,50,4,9,6,73,California,San Diego County,3095313,3095308,3104386,...,0.354751,0.235513,-0.246567,0.657077,-2.855045,4.382515,5.773072,4.745940,5.921091,2.770965
220,50,4,9,6,59,California,Orange County,3010232,3010266,3017866,...,1.992772,0.618346,-0.491825,-2.374727,-3.182714,6.033306,4.395138,3.681764,2.407607,1.587398

In [94]:
list = three_countries[three_countries["STNAME"] == "California"].head(3)["CTYNAME"].values
print(list)

['Los Angeles County' 'San Diego County' 'Orange County']

In [102]:
list = [three_countries[three_countries["STNAME"] == row[0]].head(3)["CTYNAME"].values for row in test.values]
print(list)

[array(['Los Angeles County', 'San Diego County', 'Orange County'], dtype=object), array(['Harris County', 'Dallas County', 'Tarrant County'], dtype=object), array(['Kings County', 'Queens County', 'New York County'], dtype=object)]

In [101]:
three_countries[three_countries["STNAME"] == "California"].head(3)["CTYNAME"].values

array(['Los Angeles County', 'San Diego County', 'Orange County'], dtype=object)

In [110]:
def answer_six():
    states = census_df[census_df["SUMLEV"] == 40].sort_values(by="CENSUS2010POP", \
            ascending=False)[["STNAME","CENSUS2010POP"]].head(3)
    counties = census_df[census_df["SUMLEV"] != 40].sort_values(by="CENSUS2010POP", \
            ascending=False).groupby('STNAME').head(3)
    top_counties = [counties[counties["STNAME"] == state[0]].head(3)["CTYNAME"].values for state in states.values]
    result = []
    for item in top_counties:
        result.extend(item)
    return result

In [112]:
answer_six()

['Los Angeles County',
 'San Diego County',
 'Orange County',
 'Harris County',
 'Dallas County',
 'Tarrant County',
 'Kings County',
 'Queens County',
 'New York County']

In [116]:
census_df.values.T

array([[40, 50, 50, ..., 50, 50, 50],
       [3, 3, 3, ..., 4, 4, 4],
       [6, 6, 6, ..., 8, 8, 8],
       ...,
       [1.3832821479, -2.722001942, 22.727626439, ..., -7.521839517999999,
        -2.250384934, 12.37258348],
       [1.7247180515, 2.5922703212, 20.317141924, ..., -14.74060823,
        -18.02016827, 1.533635413],
       [0.7125937237000001, -2.187333351, 18.293499115, ..., -12.60635111,
        1.4419610671, 6.935293709700001]], dtype=object)

In [118]:
census_df.columns

Index(['SUMLEV', 'REGION', 'DIVISION', 'STATE', 'COUNTY', 'STNAME', 'CTYNAME',
       'CENSUS2010POP', 'ESTIMATESBASE2010', 'POPESTIMATE2010',
       'POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013',
       'POPESTIMATE2014', 'POPESTIMATE2015', 'NPOPCHG_2010', 'NPOPCHG_2011',
       'NPOPCHG_2012', 'NPOPCHG_2013', 'NPOPCHG_2014', 'NPOPCHG_2015',
       'BIRTHS2010', 'BIRTHS2011', 'BIRTHS2012', 'BIRTHS2013', 'BIRTHS2014',
       'BIRTHS2015', 'DEATHS2010', 'DEATHS2011', 'DEATHS2012', 'DEATHS2013',
       'DEATHS2014', 'DEATHS2015', 'NATURALINC2010', 'NATURALINC2011',
       'NATURALINC2012', 'NATURALINC2013', 'NATURALINC2014', 'NATURALINC2015',
       'INTERNATIONALMIG2010', 'INTERNATIONALMIG2011', 'INTERNATIONALMIG2012',
       'INTERNATIONALMIG2013', 'INTERNATIONALMIG2014', 'INTERNATIONALMIG2015',
       'DOMESTICMIG2010', 'DOMESTICMIG2011', 'DOMESTICMIG2012',
       'DOMESTICMIG2013', 'DOMESTICMIG2014', 'DOMESTICMIG2015', 'NETMIG2010',
       'NETMIG2011', 'NETMIG2012', 'NETMIG2013', 'NETMIG2014', 'NETMIG2015',
       'RESIDUAL2010', 'RESIDUAL2011', 'RESIDUAL2012', 'RESIDUAL2013',
       'RESIDUAL2014', 'RESIDUAL2015', 'GQESTIMATESBASE2010',
       'GQESTIMATES2010', 'GQESTIMATES2011', 'GQESTIMATES2012',
       'GQESTIMATES2013', 'GQESTIMATES2014', 'GQESTIMATES2015', 'RBIRTH2011',
       'RBIRTH2012', 'RBIRTH2013', 'RBIRTH2014', 'RBIRTH2015', 'RDEATH2011',
       'RDEATH2012', 'RDEATH2013', 'RDEATH2014', 'RDEATH2015',
       'RNATURALINC2011', 'RNATURALINC2012', 'RNATURALINC2013',
       'RNATURALINC2014', 'RNATURALINC2015', 'RINTERNATIONALMIG2011',
       'RINTERNATIONALMIG2012', 'RINTERNATIONALMIG2013',
       'RINTERNATIONALMIG2014', 'RINTERNATIONALMIG2015', 'RDOMESTICMIG2011',
       'RDOMESTICMIG2012', 'RDOMESTICMIG2013', 'RDOMESTICMIG2014',
       'RDOMESTICMIG2015', 'RNETMIG2011', 'RNETMIG2012', 'RNETMIG2013',
       'RNETMIG2014', 'RNETMIG2015'],
      dtype='object')

In [121]:
df1 = pd.DataFrame(census_df.values.T, index=census_df.columns)

In [123]:
df1

,0,1,2,3,4,5,6,7,8,9,...,3183,3184,3185,3186,3187,3188,3189,3190,3191,3192
SUMLEV,40,50,50,50,50,50,50,50,50,50,...,50,50,50,50,50,50,50,50,50,50
REGION,3,3,3,3,3,3,3,3,3,3,...,4,4,4,4,4,4,4,4,4,4
DIVISION,6,6,6,6,6,6,6,6,6,6,...,8,8,8,8,8,8,8,8,8,8
STATE,1,1,1,1,1,1,1,1,1,1,...,56,56,56,56,56,56,56,56,56,56
COUNTY,0,1,3,5,7,9,11,13,15,17,...,27,29,31,33,35,37,39,41,43,45
STNAME,Alabama,Alabama,Alabama,Alabama,Alabama,Alabama,Alabama,Alabama,Alabama,Alabama,...,Wyoming,Wyoming,Wyoming,Wyoming,Wyoming,Wyoming,Wyoming,Wyoming,Wyoming,Wyoming
CTYNAME,Alabama,Autauga County,Baldwin County,Barbour County,Bibb County,Blount County,Bullock County,Butler County,Calhoun County,Chambers County,...,Niobrara County,Park County,Platte County,Sheridan County,Sublette County,Sweetwater County,Teton County,Uinta County,Washakie County,Weston County
CENSUS2010POP,4779736,54571,182265,27457,22915,57322,10914,20947,118572,34215,...,2484,28205,8667,29116,10247,43806,21294,21118,8533,7208
ESTIMATESBASE2010,4780127,54571,182265,27457,22919,57322,10915,20946,118586,34170,...,2484,28205,8667,29116,10247,43806,21294,21118,8533,7208
POPESTIMATE2010,4785161,54660,183193,27341,22861,57373,10887,20944,118437,34098,...,2492,28259,8678,29146,10244,43593,21297,21102,8545,7181
POPESTIMATE2011,4801108,55253,186659,27226,22733,57711,10629,20673,117768,33993,...,2485,28473,8701,29275,10142,44041,21482,20912,8469,7114
POPESTIMATE2012,4816089,55175,190396,27159,22642,57776,10606,20408,117286,34075,...,2475,28863,8732,29594,10418,45104,21697,20989,8443,7065
POPESTIMATE2013,4830533,55038,195126,26973,22512,57734,10628,20261,116575,34153,...,2548,29237,8728,29794,10086,45162,22347,21022,8443,7160
POPESTIMATE2014,4846411,55290,199713,26815,22549,57658,10829,20276,115993,34052,...,2530,29126,8776,30020,10039,44925,22905,20903,8316,7185
POPESTIMATE2015,4858979,55347,203709,26489,22583,57673,10696,20154,115620,34123,...,2542,29228,8812,30009,9899,44626,23125,20822,8328,7234
NPOPCHG_2010,5034,89,928,-116,-58,51,-28,-2,-149,-72,...,8,54,11,30,-3,-213,3,-16,12,-27
NPOPCHG_2011,15947,593,3466,-115,-128,338,-258,-271,-669,-105,...,-7,214,23,129,-102,448,185,-190,-76,-67
NPOPCHG_2012,14981,-78,3737,-67,-91,65,-23,-265,-482,82,...,-10,390,31,319,276,1063,215,77,-26,-49
NPOPCHG_2013,14444,-137,4730,-186,-130,-42,22,-147,-711,78,...,73,374,-4,200,-332,58,650,33,0,95
NPOPCHG_2014,15878,252,4587,-158,37,-76,201,15,-582,-101,...,-18,-111,48,226,-47,-237,558,-119,-127,25
NPOPCHG_2015,12568,57,3996,-326,34,15,-133,-122,-373,71,...,12,102,36,-11,-140,-299,220,-81,12,49
BIRTHS2010,14226,151,517,70,44,183,39,65,317,81,...,6,73,13,87,34,167,76,73,26,26
BIRTHS2011,59689,636,2187,335,266,744,169,276,1382,401,...,18,299,82,343,134,640,259,324,108,81
BIRTHS2012,59062,615,2092,300,245,710,122,241,1357,393,...,18,327,93,332,138,595,230,311,90,74
BIRTHS2013,57938,574,2160,283,259,646,132,240,1309,404,...,27,301,94,306,132,657,261,316,95,93
BIRTHS2014,58334,623,2186,260,247,618,118,267,1355,421,...,27,323,81,361,122,629,249,316,96,77
BIRTHS2015,58305,600,2240,269,253,603,123,257,1335,429,...,25,313,90,338,128,620,269,316,90,79
DEATHS2010,11089,152,532,128,34,133,52,60,312,80,...,3,86,34,84,3,76,10,49,34,9
DEATHS2011,48811,507,1825,319,278,570,132,261,1326,441,...,21,261,104,298,53,251,87,139,79,71
DEATHS2012,48357,558,1879,291,237,592,116,271,1357,475,...,29,262,105,286,38,273,61,115,105,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RBIRTH2011,12.453,11.5728,11.8264,12.2785,11.6682,12.9297,15.7092,13.2638,11.7017,11.7784,...,7.23327,10.5408,9.43668,11.7424,13.1463,14.6062,12.1087,15.4234,12.6954,11.3326
RBIRTH2012,12.2826,11.1385,11.0965,11.0325,10.7989,12.2958,11.4905,11.7329,11.5463,11.5473,...,7.25806,11.4064,10.6694,11.2793,13.4241,13.349,10.6533,14.8445,10.6433,10.438
RBIRTH2013,12.0121,10.4162,11.2056,10.4559,11.4719,11.1852,12.4329,11.8026,11.1947,11.8426,...,10.7505,10.3614,10.7675,10.3051,12.8755,14.557,11.8518,15.0437,11.2519,13.0756
RBIRTH2014,12.0563,11.2936,11.0729,9.66758,10.9629,10.7113,10.9987,13.1732,11.6525,12.3451,...,10.6341,11.0687,9.25503,12.0708,12.1242,13.9643,11.005,15.0745,11.4565,10.7354
RBIRTH2015,12.015,10.8463,11.105,10.0931,11.2116,10.4569,11.4286,12.7133,11.5279,12.5853,...,9.85804,10.7276,10.2343,11.2612,12.8398,13.8469,11.688,15.1468,10.8147,10.9578
RDEATH2011,10.1835,9.22548,9.86881,11.692,12.1946,9.90581,12.2699,12.543,11.2275,12.9533,...,8.43882,9.20116,11.9685,10.2018,5.19965,5.72837,4.06742,6.61684,9.28647,9.93354
RDEATH2012,10.0564,10.1061,9.96672,10.7015,10.4463,10.2522,10.9254,13.1934,11.5463,13.9566,...,11.6935,9.13911,12.0461,9.71649,3.6965,6.12485,2.82545,5.48913,12.4172,9.4506
RDEATH2013,10.5411,10.5795,9.86714,10.8623,12.4463,10.129,11.3026,12.8353,12.0755,13.2497,...,11.5469,9.22547,11.5693,9.83364,4.68201,6.55839,4.40469,6.47449,9.11998,10.826
RDEATH2014,10.381,9.13639,10.3536,11.5267,9.36508,10.2087,9.22776,13.0745,12.0997,14.3978,...,7.08941,8.63561,8.91225,10.1314,4.77019,5.46139,3.00539,6.20155,8.35372,9.7595
RDEATH2015,10.3716,8.44202,9.87551,11.5939,9.88212,10.2314,10.1278,11.6745,12.046,13.4067,...,7.09779,8.67121,10.348,10.5949,5.11586,5.85141,3.30219,6.56681,9.49291,10.6804
RNATURALINC2011,2.2695,2.34731,1.95754,0.586435,-0.526385,3.02388,3.4393,0.720859,0.474164,-1.1749,...,-1.20555,1.33963,-2.53179,1.54054,7.94663,8.87783,8.04133,8.80659,3.40896,1.39909
RNATURALINC2012,2.22622,1.03235,1.12981,0.330974,0.352617,2.04352,0.565105,-1.46053,0,-2.40936,...,-4.43548,2.26734,-1.3767,1.56279,9.72763,7.22419,7.82788,9.35539,-1.77389,0.987376
RNATURALINC2013,1.47098,-0.16332,1.33845,-0.406414,-0.974443,1.05619,1.13026,-1.03273,-0.880865,-1.40705,...,-0.796337,1.13597,-0.801833,0.471476,8.19352,7.99858,7.4471,8.56918,2.13194,2.24956
RNATURALINC2014,1.67532,2.1572,0.719281,-1.85915,1.59783,0.502634,1.77098,0.0986753,-0.447181,-2.05264,...,3.5447,2.43305,0.342779,1.93935,7.35404,8.50289,7.99965,8.87299,3.10281,0.97595
RNATURALINC2015,1.64342,2.40426,1.22948,-1.50083,1.32943,0.225438,1.30081,1.03883,-0.518106,-0.821415,...,2.76025,2.05641,-0.113714,0.666345,7.72394,7.99544,8.38584,8.57999,1.3218,0.277412
RINTERNATIONALMIG2011,1.02772,0.363924,1.01122,-0.146609,0.438654,0.0521358,1.95204,0.0961146,0.364091,0.910546,...,0,1.90369,0,1.16397,2.64888,0.182578,2.24409,-0.380825,-0.352651,-0.279818
RINTERNATIONALMIG2012,1.01984,0.289782,0.912334,-0.257424,0.705234,0.329041,2.3546,0.0973686,0.51903,0.852089,...,0,3.06962,-0.4589,0.917291,1.55642,0,1.43588,-0.62051,-0.354778,0
RINTERNATIONALMIG2013,1.00222,0.290347,0.881921,-0.11084,0.797272,0.34629,2.63728,0.098355,0.461813,0.908718,...,0,3.2358,-0.45819,0.976628,1.65821,0.0443135,1.63473,-0.618886,-0.236883,0
RINTERNATIONALMIG2014,1.14272,0.3263,1.07386,-0.074366,0.93207,0.485302,2.8895,0.0986753,0.550377,0.996994,...,0,3.66671,-0.457038,1.10342,2.18634,0.177606,2.16565,-0.524747,-0.238678,0
RINTERNATIONALMIG2015,1.17996,0.343466,1.09563,0,0.930604,0.485559,2.97329,0.0989364,0.569916,0.997433,...,0,3.73582,-0.454856,1.09947,2.20684,0.178669,2.0856,-0.479329,-0.240327,0
RDOMESTICMIG2011,0.00229495,7.24209,14.833,-4.72813,-5.52704,1.80738,-30.9537,-14.0327,-6.15567,-2.73164,...,-0.401849,4.58295,4.37309,0.958559,-23.7418,1.07264,-1.58956,-17.756,-11.6375,-11.7524
RDOMESTICMIG2012,-0.193196,-2.91593,17.6473,-2.50069,-5.06887,-1.17762,-5.18013,-11.6842,-4.61171,3.84909,...,0.806452,8.05776,5.39207,8.42549,15.2724,16.2432,0.972695,-4.91635,-0.827815,-8.04006
RDOMESTICMIG2013,0.381066,-3.01235,21.8457,-7.05682,-6.201,-1.74877,-1.13026,-5.65541,-5.52465,2.87272,...,29.0663,7.642,2.63459,4.54637,-40.8701,-5.33977,19.5259,-6.90295,-2.0135,12.3726
RDOMESTICMIG2014,0.582002,2.26597,19.2433,-3.90422,-0.177537,-2.06253,14.3543,1.08543,-4.46321,-2.28722,...,-12.6034,-9.25244,6.05576,3.67807,-16.5963,-14.2529,14.143,-14.2159,-17.7815,1.53364
RDOMESTICMIG2015,-0.467369,-2.5308,17.1979,-10.5433,0.177258,-1.36997,-16.1672,-6.5298,-3.37632,1.34947,...,7.49211,-2.87898,4.66227,-3.29841,-22.8709,-14.2489,-0.564849,-12.127,1.68229,6.93529
RNETMIG2011,1.03001,7.60602,15.8442,-4.87474,-5.08839,1.85951,-29.0017,-13.9366,-5.79158,-1.82109,...,-0.401849,6.48664,4.37309,2.12252,-21.0929,1.25522,0.654527,-18.1368,-11.9901,-12.0322
RNETMIG2012,0.826644,-2.62615,18.5596,-2.75811,-4.36364,-0.84858,-2.82552,-11.5869,-4.09268,4.70118,...,0.806452,11.1274,4.93317,9.34278,16.8288,16.2432,2.40858,-5.53686,-1.18259,-8.04006
RNETMIG2013,1.38328,-2.722,22.7276,-7.16766,-5.40373,-1.40248,1.50702,-5.55706,-5.06284,3.78144,...,29.0663,10.8778,2.1764,5.523,-39.2119,-5.29546,21.1607,-7.52184,-2.25038,12.3726
RNETMIG2014,1.72472,2.59227,20.3171,-3.97858,0.754533,-1.57723,17.2438,1.1841,-3.91283,-1.29023,...,-12.6034,-5.58573,5.59872,4.78149,-14.4099,-14.0753,16.3087,-14.7406,-18.0202,1.53364
RNETMIG2015,0.712594,-2.18733,18.2935,-10.5433,1.10786,-0.884411,-13.194,-6.43087,-2.80641,2.3469,...,7.49211,0.856839,4.20741,-2.19894,-20.6641,-14.0702,1.52075,-12.6064,1.44196,6.93529

In [132]:
min_pop = census_df.loc[:, "POPESTIMATE2010":"POPESTIMATE2015"]

In [133]:
min_pop.head()

,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015
0,4785161,4801108,4816089,4830533,4846411,4858979
1,54660,55253,55175,55038,55290,55347
2,183193,186659,190396,195126,199713,203709
3,27341,27226,27159,26973,26815,26489
4,22861,22733,22642,22512,22549,22583

In [136]:
min_data = min_pop.min(axis=1)
max_data = min_pop.max(axis=1)
rest_data = max_data - min_data

In [137]:
min_data.head()

0    4785161
1      54660
2     183193
3      26489
4      22512
dtype: int64

In [139]:
max_data.head()

0    4858979
1      55347
2     203709
3      27341
4      22861
dtype: int64

In [141]:
rest_data.head()

0    73818
1      687
2    20516
3      852
4      349
dtype: int64

In [144]:
max_rest = rest_data.head().argmax()
print(max_rest)

0

In [146]:
max_rest = rest_data.head().max()
print(max_rest)

73818

In [151]:
census = census_df.loc[rest_data.head().argmax(),"CTYNAME"]

In [154]:
print(census)

Alabama

In [158]:
remove_states = min_pop = census_df[census_df["SUMLEV"] != 40]

In [159]:
min_pop = remove_states.loc[:, "POPESTIMATE2010":"POPESTIMATE2015"]

In [160]:
min_data = min_pop.min(axis=1)
max_data = min_pop.max(axis=1)
rest_data = max_data - min_data

In [162]:
census = census_df.loc[rest_data.head().argmax(),"CTYNAME"]

In [164]:
print(census)

Baldwin County

In [166]:
census_df[census_df["CTYNAME"] == "Baldwin County"]

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.83296,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
402,50,3,5,13,9,Georgia,Baldwin County,45720,45835,45702,...,-17.57748,26.847544,-9.633245,-8.721183,-8.786056,-16.828565,27.590275,-8.769277,-7.742497,-7.800090

In [241]:
def answer_seven():
    population = census_df[census_df["SUMLEV"] != 40].loc[:, "POPESTIMATE2010":"POPESTIMATE2015"]
    rest_data = population.max(axis=1) -  min_pop.min(axis=1)
    return census_df.loc[rest_data.argmax(),"CTYNAME"]

In [242]:
answer_seven()

'Harris County'

In [179]:
census_df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [206]:
first_filter = census_df[census_df["REGION"].isin([1,2])]
first_filter.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
314,40,1,1,9,0,Connecticut,Connecticut,3574097,3574118,3579717,...,-3.724400,-5.311208,-4.730271,-7.567093,-7.687268,0.775510,-1.066084,-0.278693,-2.376831,-2.463243
315,50,1,1,9,1,Connecticut,Fairfield County,916829,916850,919744,...,-0.228261,-3.030708,-2.070291,-6.633789,-7.385939,6.119788,2.687406,4.096896,0.441829,-0.338989
316,50,1,1,9,3,Connecticut,Hartford County,894014,894029,895303,...,-5.037297,-6.324143,-5.237664,-8.636074,-8.135161,-0.025666,-1.662136,-0.314193,-2.840433,-2.327200
317,50,1,1,9,5,Connecticut,Litchfield County,189927,189927,189773,...,-4.103317,-7.183847,-2.812353,-7.951141,-5.931948,-3.290047,-6.450584,-1.983618,-6.939080,-4.906204
318,50,1,1,9,7,Connecticut,Middlesex County,165676,165676,165628,...,1.410378,-6.716791,-2.617825,-4.987002,-6.526367,3.598271,-4.522077,-0.308335,-2.272328,-3.807554

In [209]:
second_filter = first_filter[first_filter["CTYNAME"].str.startswith("Washington")]
second_filter

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
703,50,2,3,17,189,Illinois,Washington County,14716,14716,14701,...,-8.057633,2.192006,-12.192182,-2.775850,-10.605638,-8.125918,2.123506,-12.192182,-2.775850,-10.605638
799,50,2,3,18,175,Indiana,Washington County,28262,28262,28284,...,-3.683894,-9.517699,-5.310179,0.717901,-5.454774,-3.258829,-9.161231,-4.879624,1.148641,-5.024134
896,50,2,4,19,183,Iowa,Washington County,21704,21704,21697,...,5.743693,2.468684,-0.364282,0.272171,1.849596,5.881542,2.560117,-0.273212,0.408256,1.984933
1005,50,2,4,20,201,Kansas,Washington County,5799,5799,5782,...,10.504563,-18.164519,-18.821460,-5.501819,-6.948156,12.054417,-16.780555,-17.238347,-3.549561,-4.988420
1211,50,1,1,23,29,Maine,Washington County,32856,32856,32824,...,0.213626,-3.280699,-4.262285,-9.111049,-4.284274,0.366217,-2.790127,-3.829879,-8.643015,-3.811744
1419,50,2,4,27,163,Minnesota,Washington County,238136,238134,238995,...,2.555118,3.260957,2.285952,3.072543,0.678755,4.178076,4.907905,4.009584,5.040262,2.615204
1618,50,2,4,29,221,Missouri,Washington County,25195,25196,25177,...,-5.130755,-2.389867,0.079577,-1.592420,-11.511311,-5.011435,-2.389867,0.079577,-1.592420,-11.511311
1770,50,2,4,31,177,Nebraska,Washington County,20234,20234,20275,...,-1.874784,-1.331459,-4.492607,-0.889284,-3.998716,-1.825448,-1.282146,-4.393868,-0.790475,-3.899983
1918,50,1,2,36,115,New York,Washington County,63216,63216,63292,...,-3.719090,-1.776030,-4.165839,-4.954213,-2.342897,-3.418398,-1.522311,-3.879636,-4.634587,-2.021953
2162,50,2,3,39,167,Ohio,Washington County,61778,61778,61708,...,0.129798,0.780050,-0.455611,-2.137467,0.016355,0.227147,1.023816,-0.162718,-1.778503,0.376173
2345,50,1,2,42,125,Pennsylvania,Washington County,207820,207820,207877,...,3.683135,3.260434,1.219337,2.113561,1.656917,4.062988,3.750219,1.742595,2.762039,2.305276
2355,50,1,1,44,9,Rhode Island,Washington County,126979,127094,127085,...,-4.669304,-2.659574,1.551904,1.400112,0.506035,-3.533527,-1.788880,2.462459,2.428442,1.533918
2863,50,1,1,50,23,Vermont,Washington County,59534,59526,59570,...,-1.578161,-5.617505,-3.407759,-4.097008,-6.278073,-1.376694,-5.281128,-3.087227,-3.741482,-5.920784
3163,50,2,3,55,131,Wisconsin,Washington County,131887,131885,131967,...,-0.794876,0.785279,-2.215465,1.601149,-0.434498,-0.431504,1.162817,-1.763330,2.104796,0.059931

In [202]:
third_filter = second_filter[second_filter["POPESTIMATE2015"] > second_filter["POPESTIMATE2014"]]
third_filter.loc[:,['STNAME', 'CTYNAME']]

            STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County

In [210]:
def answer_eight():
    first_filter = census_df[census_df["REGION"].isin([1,2])]
    second_filter = first_filter[first_filter["CTYNAME"].str.startswith("Washington")]
    third_filter = second_filter[second_filter["POPESTIMATE2015"] > second_filter["POPESTIMATE2014"]]
    return third_filter.loc[:,['STNAME', 'CTYNAME']]

In [231]:
answer_eight()

            STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County

In [233]:
    population = census_df[census_df["SUMLEV"] != 40].loc[:, "POPESTIMATE2010":"POPESTIMATE2015"]

In [235]:
population

,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015
1,54660,55253,55175,55038,55290,55347
2,183193,186659,190396,195126,199713,203709
3,27341,27226,27159,26973,26815,26489
4,22861,22733,22642,22512,22549,22583
5,57373,57711,57776,57734,57658,57673
6,10887,10629,10606,10628,10829,10696
7,20944,20673,20408,20261,20276,20154
8,118437,117768,117286,116575,115993,115620
9,34098,33993,34075,34153,34052,34123
10,25976,26080,26023,26084,25995,25859
11,43665,43739,43697,43795,43921,43943
12,13841,13593,13543,13378,13289,13170
13,25767,25570,25144,25116,24847,24675
14,13880,13670,13456,13467,13538,13555
15,14973,14971,14921,15028,15072,15018
16,50177,50448,51173,50755,50831,51211
17,54514,54443,54472,54471,54480,54354
18,13208,13121,12996,12875,12662,12672
19,11758,11348,11195,11059,10807,10724
20,37796,38060,37818,37830,37888,37835
21,13853,13896,13951,13932,13948,13963
22,80473,80469,80374,80756,81221,82005
23,50358,50109,50324,49833,49501,49565
24,43803,43178,42777,42021,41662,41131
25,71142,71387,70942,70869,71012,71130
26,79465,80012,80432,80883,81022,81468
27,38309,38213,38034,37857,37784,37789
28,104442,104236,104235,103852,103452,103057
29,17231,17062,16960,16857,16842,16759
30,31734,31729,31648,31507,31592,31696
...,...,...,...,...,...,...
3162,15930,15784,15831,15657,15678,15552
3163,131967,132225,132649,132758,133301,133674
3164,390076,390808,392710,394025,395335,396488
3165,52422,52342,52035,52213,52088,51945
3166,24506,24581,24484,24332,24173,24033
3167,167059,167630,168717,169486,169639,169546
3168,74807,74647,74384,73996,73597,73435
3170,36428,36908,37396,37647,37918,37956
3171,11672,11745,11785,12002,11919,12022
3172,46244,46600,47881,48121,48243,49220
3173,15837,15817,15678,15787,15856,15559
3174,13826,13728,14025,14343,14172,14236
3175,7114,7129,7148,7160,7264,7444
3176,40222,40591,41129,41024,40717,40315
3177,13408,13597,13666,13565,13509,13383
3178,4813,4818,4846,4846,4793,4741
3179,8581,8636,8610,8619,8552,8585
3180,92271,92663,94894,96006,96469,97121
3181,18091,18022,17943,18328,18564,18722
3182,75472,76420,78699,81156,81603,82178
3183,2492,2485,2475,2548,2530,2542
3184,28259,28473,28863,29237,29126,29228
3185,8678,8701,8732,8728,8776,8812
3186,29146,29275,29594,29794,30020,30009
3187,10244,10142,10418,10086,10039,9899
3188,43593,44041,45104,45162,44925,44626
3189,21297,21482,21697,22347,22905,23125
3190,21102,20912,20989,21022,20903,20822
3191,8545,8469,8443,8443,8316,8328
3192,7181,7114,7065,7160,7185,7234

In [237]:
    population = census_df[census_df["SUMLEV"] != 40].loc[:, "POPESTIMATE2010":"POPESTIMATE2015"]
    rest_data = population.max(axis=1) -  population.min(axis=1)
    rest_data

1         687
2       20516
3         852
4         349
5         403
6         281
7         790
8        2817
9         160
10        225
11        278
12        671
13       1092
14        424
15        151
16       1034
17        160
18        546
19       1034
20        264
21        110
22       1631
23        857
24       2672
25        518
26       2003
27        525
28       1385
29        472
30        227
        ...
3162      378
3163     1707
3164     6412
3165      477
3166      548
3167     2580
3168     1372
3170     1528
3171      350
3172     2976
3173      297
3174      615
3175      330
3176      907
3177      283
3178      105
3179       84
3180     4850
3181      779
3182     6706
3183       73
3184      978
3185      134
3186      874
3187      519
3188     1569
3189     1828
3190      280
3191      229
3192      169
dtype: int64

In [239]:
population.max(axis=1)

1        55347
2       203709
3        27341
4        22861
5        57776
6        10887
7        20944
8       118437
9        34153
10       26084
11       43943
12       13841
13       25767
14       13880
15       15072
16       51211
17       54514
18       13208
19       11758
20       38060
21       13963
22       82005
23       50358
24       43803
25       71387
26       81468
27       38309
28      104442
29       17231
30       31734
         ...
3162     15930
3163    133674
3164    396488
3165     52422
3166     24581
3167    169639
3168     74807
3170     37956
3171     12022
3172     49220
3173     15856
3174     14343
3175      7444
3176     41129
3177     13666
3178      4846
3179      8636
3180     97121
3181     18722
3182     82178
3183      2548
3184     29237
3185      8812
3186     30020
3187     10418
3188     45162
3189     23125
3190     21102
3191      8545
3192      7234
dtype: int64

In [244]:
population.min(axis=1)

1        54660
2       183193
3        26489
4        22512
5        57373
6        10606
7        20154
8       115620
9        33993
10       25859
11       43665
12       13170
13       24675
14       13456
15       14921
16       50177
17       54354
18       12662
19       10724
20       37796
21       13853
22       80374
23       49501
24       41131
25       70869
26       79465
27       37784
28      103057
29       16759
30       31507
         ...
3162     15552
3163    131967
3164    390076
3165     51945
3166     24033
3167    167059
3168     73435
3170     36428
3171     11672
3172     46244
3173     15559
3174     13728
3175      7114
3176     40222
3177     13383
3178      4741
3179      8552
3180     92271
3181     17943
3182     75472
3183      2475
3184     28259
3185      8678
3186     29146
3187      9899
3188     43593
3189     21297
3190     20822
3191      8316
3192      7065
dtype: int64

I have missunderstood question #6

Question 6

Only looking at the three most populous counties for each state, what are the three most populous states (in order of highest population to lowest population)? Use CENSUS2010POP.

This function should return a list of string values.

In [246]:
def answer_six():
    states = census_df[census_df["SUMLEV"] == 40].sort_values(by="CENSUS2010POP", \
            ascending=False)[["STNAME","CENSUS2010POP"]].head(3)
    counties = census_df[census_df["SUMLEV"] != 40].sort_values(by="CENSUS2010POP", \
            ascending=False).groupby('STNAME').head(3)
    top_counties = [counties[counties["STNAME"] == state[0]].head(3)["CTYNAME"].values for state in states.values]
    result = []
    for item in top_counties:
        result.extend(item)
    return result

In [250]:
# These are the three countries with higes population
# I have removed the sumlev that belong to the state it self
counties = census_df[census_df["SUMLEV"] != 40].sort_values(by="CENSUS2010POP", \
            ascending=False).groupby('STNAME').head(3)
counties.sort_values(by="STNAME").head(10)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
45,50,3,6,1,89,Alabama,Madison County,334811,334811,336138,...,4.170416,3.438521,6.367708,4.064107,2.480087,5.739131,4.880766,7.818211,5.734524,4.180881
37,50,3,6,1,73,Alabama,Jefferson County,658466,658350,658116,...,-4.138628,-4.492646,-1.664873,-0.970225,-3.337536,-2.985041,-3.536344,-0.647113,0.221333,-2.126089
49,50,3,6,1,97,Alabama,Mobile County,412992,413143,413332,...,-5.242052,-3.722733,-3.181655,-2.311087,-3.873201,-3.751237,-2.281051,-1.753896,-0.759909,-2.288272
71,50,4,9,2,20,Alaska,Anchorage Municipality,291826,291826,293405,...,-3.788123,-7.563712,-3.962343,-18.897015,-19.781254,-0.969922,-2.652342,0.053320,-14.789980,-15.280810
85,50,4,9,2,170,Alaska,Matanuska-Susitna Borough,88995,88995,89761,...,13.050517,11.474315,12.906763,15.008086,18.697964,13.391923,12.303913,13.528903,15.605525,19.349985
76,50,4,9,2,90,Alaska,Fairbanks North Star Borough,97581,97581,98289,...,-17.339069,5.430293,-9.147023,-33.436804,-13.859157,-15.791483,10.618791,-4.926084,-29.823633,-8.984834
106,50,4,8,4,13,Arizona,Maricopa County,3817117,3817357,3825597,...,2.444413,9.232973,7.879873,8.318210,9.123309,4.726436,11.527593,10.390177,11.203958,11.985998
110,50,4,8,4,21,Arizona,Pinal County,375770,375770,379384,...,-13.828377,4.308298,0.966512,17.437436,18.998761,-11.594501,6.465078,3.391910,20.212795,21.745600
109,50,4,8,4,19,Arizona,Pima County,980263,980263,981870,...,0.874159,-0.248360,-1.381638,1.036139,0.159859,2.781876,2.000003,0.854104,3.582023,2.777186
118,50,3,7,5,7,Arkansas,Benton County,221339,221344,223010,...,11.164115,11.786353,9.333699,11.268649,16.254517,13.816535,14.533319,12.296171,14.648828,19.555772

Now I think I have to group by stname and do the sum

In [259]:
counties[counties["STNAME"] == "Alabama"]

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
37,50,3,6,1,73,Alabama,Jefferson County,658466,658350,658116,...,-4.138628,-4.492646,-1.664873,-0.970225,-3.337536,-2.985041,-3.536344,-0.647113,0.221333,-2.126089
49,50,3,6,1,97,Alabama,Mobile County,412992,413143,413332,...,-5.242052,-3.722733,-3.181655,-2.311087,-3.873201,-3.751237,-2.281051,-1.753896,-0.759909,-2.288272
45,50,3,6,1,89,Alabama,Madison County,334811,334811,336138,...,4.170416,3.438521,6.367708,4.064107,2.480087,5.739131,4.880766,7.818211,5.734524,4.180881

In [258]:
counties.groupby('STNAME').sum()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
STNAME,,,,,,,,,,,,,,,,,,,,,
Alabama,150,9,18,3,259,1406269,1406304,1407586,1410415,1414150,...,-5.210264,-4.776858,1.521180,0.782795,-4.730649,-0.997146,-0.936629,5.417202,5.195948,-0.233479
Alaska,150,12,27,6,280,478402,478402,481455,486320,492774,...,-8.076675,9.340896,-0.202602,-37.325733,-14.942448,-3.369482,20.270363,8.656139,-29.008088,-4.915660
Arizona,150,12,24,12,53,5173150,5173390,5186851,5238025,5320782,...,-10.509806,13.292912,7.464747,26.791785,28.281929,-4.086189,19.992674,14.636191,34.998776,36.508784
Arkansas,150,9,21,15,269,807152,807193,810664,822608,833594,...,18.012611,15.487208,19.531981,14.860365,18.764610,25.429853,23.248130,27.588498,23.927394,27.755652
California,150,12,27,18,169,15924150,15924274,15948261,16094942,16244137,...,-2.651916,-3.217407,-5.070710,-7.111949,-12.065453,10.408013,10.545720,9.005753,8.543736,3.920882
Colorado,150,12,24,24,77,1794424,1794276,1804943,1842353,1876037,...,27.771666,18.792262,22.893340,20.143692,28.235188,35.559626,29.992427,33.123220,31.120035,39.785916
Connecticut,150,3,3,27,13,2673320,2673353,2678448,2689918,2696308,...,-10.505871,-14.933884,-14.110408,-22.841714,-23.955999,5.019660,-0.710943,1.026736,-5.165822,-6.286792
Delaware,150,9,15,30,9,897934,897936,899791,907916,917099,...,15.045588,18.288721,17.688504,24.173863,23.526694,21.669717,26.005809,24.962252,32.310212,31.748738
District of Columbia,50,3,5,11,1,601723,601767,605126,620472,635342,...,11.560071,10.052444,9.457678,1.480094,5.601833,17.028422,15.972111,15.634120,8.378037,12.434838
Florida,150,9,15,36,196,5564635,5566299,5585605,5706159,5788070,...,19.535263,7.240553,-0.582439,-0.392163,-1.175483,49.647485,34.098255,28.153612,31.932188,30.701761
Georgia,150,9,15,39,345,2417795,2417794,2426797,2473119,2526214,...,9.891342,20.125342,-2.016731,5.361659,8.569580,24.893468,34.448704,13.541065,23.031227,26.019134
Hawaii,150,12,27,45,13,1293120,1293121,1296681,1310343,1324001,...,0.304948,-2.073955,4.976034,4.110728,-6.897144,13.241273,13.677011,20.498440,20.945511,10.375761
Idaho,150,12,24,48,83,719782,719782,721774,733583,745076,...,21.156309,20.416523,39.282258,40.029875,38.329324,23.136657,22.690841,41.716974,42.887869,41.265480
Illinois,150,6,9,51,171,6815061,6815323,6821742,6841179,6862181,...,-19.864534,-18.494617,-14.252015,-22.842075,-26.515534,-11.715929,-9.144169,-4.775492,-12.003940,-15.246911
Indiana,150,6,9,54,189,1754727,1754785,1756545,1764431,1772799,...,-10.433246,-11.457208,-7.153718,-10.590767,-15.110314,-4.728154,-5.774969,-0.926905,-3.437836,-7.914154
Iowa,150,6,12,57,429,807090,807085,809690,818946,828206,...,10.224301,7.367100,8.578369,8.213186,4.478413,15.126672,12.542500,14.133403,14.492295,10.682602
Kansas,150,6,12,60,441,1220478,1220478,1223457,1233018,1243138,...,-3.680603,-4.285019,-8.235070,-5.861575,-7.106096,0.936397,1.058987,-2.712322,0.352563,-0.868897
Kentucky,150,9,18,63,295,1196619,1196609,1198959,1208132,1218451,...,2.041586,4.339977,6.044024,-6.894043,-4.559268,8.899797,12.132588,14.303034,2.446220,4.752496
Louisiana,150,9,21,66,155,1216552,1216559,1221363,1236168,1248559,...,16.067513,9.285817,5.581655,-5.324700,-6.212744,24.770407,18.030998,14.562976,4.808918,3.972428
Maine,150,3,3,69,55,632728,632727,632530,634807,636742,...,5.439338,2.332435,1.893981,7.760245,-2.475211,8.652369,5.680685,5.444405,11.790245,1.571928
Maryland,150,9,15,72,69,2640226,2640278,2648262,2681555,2707976,...,-1.949270,-8.687433,-7.325764,-11.054690,-18.189328,18.907110,11.010090,13.617174,12.357439,5.067886
Massachusetts,150,3,3,75,53,3044796,3044843,3053237,3079303,3104077,...,-1.588264,-4.667380,-0.371774,-4.445578,-8.789620,14.461523,11.508623,16.790373,15.112151,10.585699
Michigan,150,6,9,78,387,3863924,3863990,3859376,3855485,3862198,...,-13.750706,-6.304689,-7.329113,-10.569082,-15.210222,-5.805868,2.453482,2.196919,0.265012,-4.420837
Minnesota,150,6,12,81,213,2059617,2059580,2062866,2087359,2110830,...,0.115184,-3.172176,-0.022561,-4.914112,-12.228149,12.258918,8.833751,12.849671,9.536281,2.108017
Mississippi,150,9,18,84,129,593642,593734,595385,603181,608248,...,18.479441,6.651550,-2.395420,2.685593,1.504391,21.165781,12.097544,1.561792,6.668289,6.057987
Missouri,150,6,12,87,467,2033597,2033599,2035634,2039626,2047381,...,-7.928856,-2.678610,0.210444,3.065942,2.931710,-3.324430,2.269915,5.557987,9.110738,8.953494
Montana,150,12,24,90,203,348199,348199,348729,351209,354610,...,6.891466,13.742662,22.238780,23.008659,22.233419,8.836465,15.110271,23.773530,24.801700,23.985999
Nebraska,150,6,12,93,317,961357,961363,964606,977333,991053,...,9.744942,8.747325,12.458774,9.973036,7.420047,16.304521,18.342085,21.447860,19.758069,17.503547
Nevada,150,12,24,96,544,2427950,2427970,2430543,2447061,2481975,...,-6.180602,9.425433,1.470494,25.338374,20.357812,-1.049348,14.166924,6.706253,31.454746,26.551405
New Hampshire,150,3,3,99,39,842389,842383,842779,844532,847465,...,-3.597147,0.793309,-5.177843,3.670753,-0.035073,0.392800,4.921409,-0.922877,8.607071,4.912855
New Jersey,150,3,6,102,39,2498943,2498964,2502741,2518540,2532351,...,-17.135497,-18.298175,-15.020502,-17.841002,-21.919035,5.131527,2.542641,7.563613,7.772376,3.467642
New Mexico,150,12,24,105,63,1015967,1015967,1018781,1027869,1033702,...,6.841076,-1.816738,-13.223643,-11.522041,-13.433344,11.292796,3.296527,-7.960010,-5.335899,-7.056215
New York,150,3,6,108,189,6321295,6321125,6334517,6415677,6478955,...,-16.053963,-21.963170,-25.961890,-37.692288,-33.162537,13.875961,6.153060,4.616700,-3.037706,1.208424
North Carolina,150,9,15,111,383,2309027,2309093,2319768,2369568,2422033,...,25.312212,28.008135,25.154246,22.976785,21.835781,36.472519,38.823980,36.778592,36.039950,34.696044
North Dakota,150,6,12,114,67,297947,297947,298983,303074,311033,...,2.692011,38.785415,56.880875,25.875697,25.419591,10.020265,48.809998,66.553192,36.216662,35.774480
Ohio,150,6,9,117,145,3245910,3246028,3246792,3250531,3265804,...,-17.098905,-7.620338,-5.726177,-6.364582,-9.924976,-9.125833,0.669173,3.153181,3.761166,0.115442
Oklahoma,150,9,21,120,279,1577791,1577828,1583215,1600716,1623833,...,12.597213,16.491738,19.820786,1.105175,15.831821,18.558553,24.113037,27.323434,9.464147,24.279329
Oregon,150,12,27,123,123,1641036,1641036,1645884,1667675,1690502,...,14.068544,16.751534,13.053141,21.291598,27.967503,21.001814,23.620660,20.653352,30.056981,36.655815
Pennsylvania,150,3,6,126,195,3549228,3549238,3553334,3572339,3591166,...,-0.880698,-2.818224,-6.144355,-12.782001,-13.772559,9.088422,7.823320,5.218530,0.277250,-0.766701
Rhode Island,150,3,3,132,19,919804,919915,920213,919578,920252,...,-15.458351,-11.890145,-6.295962,-2.471444,-8.225610,-7.756017,-4.797897,1.126521,6.035907,0.258276
South Carolina,150,9,15,135,143,1185938,1185929,1189652,1206326,1225520,...,20.294983,24.813239,24.371662,27.575407,32.642686,25.656874,31.305282,29.806186,33.369922,38.925674
South Dakota,150,6,12,138,285,315244,315236,316548,321222,328352,...,25.027157,38.457869,39.009049,31.555417,10.483546,29.199692,43.623685,43.560252,36.495586,15.464339
Tennessee,150,9,18,141,287,1986551,1986536,1989784,2005858,2030087,...,3.027817,13.627939,-1.609775,0.058095,-3.420610,9.757221,20.419644,5.627131,8.292194,4.826775
Texas,150,9,21,144,753,8269632,8270250,8298179,8439027,8601286,...,7.142972,14.863483,7.496872,9.559581,8.836789,20.398518,27.431740,21.195186,25.187793,24.341074
Utah,150,12,24,147,95,1852698,1852707,1861122,1891350,1921000,...,-1.832636,-2.057396,9.609927,0.778047,7.631529,3.711783,3.850248,15.725643,7.625366,14.498109
Vermont,150,3,3,150,51,277721,277712,277960,278568,279025,...,-5.090284,-10.625325,-6.050549,-11.464772,-15.602828,-2.099284,-6.866927,-2.110827,-6.866679,-10.977152
Virginia,150,9,15,153,1022,1921722,1921623,1932244,1968690,1997826,...,12.596562,-4.231819,-6.248882,-26.775135,-24.921180,29.448962,16.145147,12.543525,-6.245564,-3.676054
Washington,150,12,27,159,147,3439809,3439815,3448636,3498362,3554031,...,7.686642,10.740119,13.547908,16.463148,15.168146,18.990933,24.195834,26.681489,30.894210,29.698682
West Virginia,150,9,15,162,53,393551,393546,393954,394211,396034,...,3.109074,9.276608,6.071358,3.327349,-2.494480,5.187991,11.942221,8.668154,6.330484,0.502821
Wisconsin,150,6,9,165,237,1825699,1825749,1827564,1839005,1851367,...,0.284569,1.401349,-2.150699,-4.435622,-6.843451,6.180482,7.956099,4.949570,3.771220,1.353432
Wyoming,150,12,24,168,51,213321,213464,213987,215683,221474,...,3.145411,54.214456,23.214178,-10.735517,11.134846,4.066748,57.222746,25.171833,-8.827814,13.445908

In [261]:
def answer_six():
    counties = census_df[census_df["SUMLEV"] != 40].sort_values(by="CENSUS2010POP", \
            ascending=False).groupby('STNAME').head(3).groupby('STNAME').sum()
    return counties.sort_values(by="CENSUS2010POP", ascending=False)

In [263]:
answer_six()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
STNAME,,,,,,,,,,,,,,,,,,,,,
California,150,12,27,18,169,15924150,15924274,15948261,16094942,16244137,...,-2.651916,-3.217407,-5.070710,-7.111949,-12.065453,10.408013,10.545720,9.005753,8.543736,3.920882
Texas,150,9,21,144,753,8269632,8270250,8298179,8439027,8601286,...,7.142972,14.863483,7.496872,9.559581,8.836789,20.398518,27.431740,21.195186,25.187793,24.341074
Illinois,150,6,9,51,171,6815061,6815323,6821742,6841179,6862181,...,-19.864534,-18.494617,-14.252015,-22.842075,-26.515534,-11.715929,-9.144169,-4.775492,-12.003940,-15.246911
New York,150,3,6,108,189,6321295,6321125,6334517,6415677,6478955,...,-16.053963,-21.963170,-25.961890,-37.692288,-33.162537,13.875961,6.153060,4.616700,-3.037706,1.208424
Florida,150,9,15,36,196,5564635,5566299,5585605,5706159,5788070,...,19.535263,7.240553,-0.582439,-0.392163,-1.175483,49.647485,34.098255,28.153612,31.932188,30.701761
Arizona,150,12,24,12,53,5173150,5173390,5186851,5238025,5320782,...,-10.509806,13.292912,7.464747,26.791785,28.281929,-4.086189,19.992674,14.636191,34.998776,36.508784
Michigan,150,6,9,78,387,3863924,3863990,3859376,3855485,3862198,...,-13.750706,-6.304689,-7.329113,-10.569082,-15.210222,-5.805868,2.453482,2.196919,0.265012,-4.420837
Pennsylvania,150,3,6,126,195,3549228,3549238,3553334,3572339,3591166,...,-0.880698,-2.818224,-6.144355,-12.782001,-13.772559,9.088422,7.823320,5.218530,0.277250,-0.766701
Washington,150,12,27,159,147,3439809,3439815,3448636,3498362,3554031,...,7.686642,10.740119,13.547908,16.463148,15.168146,18.990933,24.195834,26.681489,30.894210,29.698682
Ohio,150,6,9,117,145,3245910,3246028,3246792,3250531,3265804,...,-17.098905,-7.620338,-5.726177,-6.364582,-9.924976,-9.125833,0.669173,3.153181,3.761166,0.115442
Massachusetts,150,3,3,75,53,3044796,3044843,3053237,3079303,3104077,...,-1.588264,-4.667380,-0.371774,-4.445578,-8.789620,14.461523,11.508623,16.790373,15.112151,10.585699
Connecticut,150,3,3,27,13,2673320,2673353,2678448,2689918,2696308,...,-10.505871,-14.933884,-14.110408,-22.841714,-23.955999,5.019660,-0.710943,1.026736,-5.165822,-6.286792
Maryland,150,9,15,72,69,2640226,2640278,2648262,2681555,2707976,...,-1.949270,-8.687433,-7.325764,-11.054690,-18.189328,18.907110,11.010090,13.617174,12.357439,5.067886
New Jersey,150,3,6,102,39,2498943,2498964,2502741,2518540,2532351,...,-17.135497,-18.298175,-15.020502,-17.841002,-21.919035,5.131527,2.542641,7.563613,7.772376,3.467642
Nevada,150,12,24,96,544,2427950,2427970,2430543,2447061,2481975,...,-6.180602,9.425433,1.470494,25.338374,20.357812,-1.049348,14.166924,6.706253,31.454746,26.551405
Georgia,150,9,15,39,345,2417795,2417794,2426797,2473119,2526214,...,9.891342,20.125342,-2.016731,5.361659,8.569580,24.893468,34.448704,13.541065,23.031227,26.019134
North Carolina,150,9,15,111,383,2309027,2309093,2319768,2369568,2422033,...,25.312212,28.008135,25.154246,22.976785,21.835781,36.472519,38.823980,36.778592,36.039950,34.696044
Minnesota,150,6,12,81,213,2059617,2059580,2062866,2087359,2110830,...,0.115184,-3.172176,-0.022561,-4.914112,-12.228149,12.258918,8.833751,12.849671,9.536281,2.108017
Missouri,150,6,12,87,467,2033597,2033599,2035634,2039626,2047381,...,-7.928856,-2.678610,0.210444,3.065942,2.931710,-3.324430,2.269915,5.557987,9.110738,8.953494
Tennessee,150,9,18,141,287,1986551,1986536,1989784,2005858,2030087,...,3.027817,13.627939,-1.609775,0.058095,-3.420610,9.757221,20.419644,5.627131,8.292194,4.826775
Virginia,150,9,15,153,1022,1921722,1921623,1932244,1968690,1997826,...,12.596562,-4.231819,-6.248882,-26.775135,-24.921180,29.448962,16.145147,12.543525,-6.245564,-3.676054
Utah,150,12,24,147,95,1852698,1852707,1861122,1891350,1921000,...,-1.832636,-2.057396,9.609927,0.778047,7.631529,3.711783,3.850248,15.725643,7.625366,14.498109
Wisconsin,150,6,9,165,237,1825699,1825749,1827564,1839005,1851367,...,0.284569,1.401349,-2.150699,-4.435622,-6.843451,6.180482,7.956099,4.949570,3.771220,1.353432
Colorado,150,12,24,24,77,1794424,1794276,1804943,1842353,1876037,...,27.771666,18.792262,22.893340,20.143692,28.235188,35.559626,29.992427,33.123220,31.120035,39.785916
Indiana,150,6,9,54,189,1754727,1754785,1756545,1764431,1772799,...,-10.433246,-11.457208,-7.153718,-10.590767,-15.110314,-4.728154,-5.774969,-0.926905,-3.437836,-7.914154
Oregon,150,12,27,123,123,1641036,1641036,1645884,1667675,1690502,...,14.068544,16.751534,13.053141,21.291598,27.967503,21.001814,23.620660,20.653352,30.056981,36.655815
Oklahoma,150,9,21,120,279,1577791,1577828,1583215,1600716,1623833,...,12.597213,16.491738,19.820786,1.105175,15.831821,18.558553,24.113037,27.323434,9.464147,24.279329
Alabama,150,9,18,3,259,1406269,1406304,1407586,1410415,1414150,...,-5.210264,-4.776858,1.521180,0.782795,-4.730649,-0.997146,-0.936629,5.417202,5.195948,-0.233479
Hawaii,150,12,27,45,13,1293120,1293121,1296681,1310343,1324001,...,0.304948,-2.073955,4.976034,4.110728,-6.897144,13.241273,13.677011,20.498440,20.945511,10.375761
Kansas,150,6,12,60,441,1220478,1220478,1223457,1233018,1243138,...,-3.680603,-4.285019,-8.235070,-5.861575,-7.106096,0.936397,1.058987,-2.712322,0.352563,-0.868897
Louisiana,150,9,21,66,155,1216552,1216559,1221363,1236168,1248559,...,16.067513,9.285817,5.581655,-5.324700,-6.212744,24.770407,18.030998,14.562976,4.808918,3.972428
Kentucky,150,9,18,63,295,1196619,1196609,1198959,1208132,1218451,...,2.041586,4.339977,6.044024,-6.894043,-4.559268,8.899797,12.132588,14.303034,2.446220,4.752496
South Carolina,150,9,15,135,143,1185938,1185929,1189652,1206326,1225520,...,20.294983,24.813239,24.371662,27.575407,32.642686,25.656874,31.305282,29.806186,33.369922,38.925674
New Mexico,150,12,24,105,63,1015967,1015967,1018781,1027869,1033702,...,6.841076,-1.816738,-13.223643,-11.522041,-13.433344,11.292796,3.296527,-7.960010,-5.335899,-7.056215
Nebraska,150,6,12,93,317,961357,961363,964606,977333,991053,...,9.744942,8.747325,12.458774,9.973036,7.420047,16.304521,18.342085,21.447860,19.758069,17.503547
Rhode Island,150,3,3,132,19,919804,919915,920213,919578,920252,...,-15.458351,-11.890145,-6.295962,-2.471444,-8.225610,-7.756017,-4.797897,1.126521,6.035907,0.258276
Delaware,150,9,15,30,9,897934,897936,899791,907916,917099,...,15.045588,18.288721,17.688504,24.173863,23.526694,21.669717,26.005809,24.962252,32.310212,31.748738
New Hampshire,150,3,3,99,39,842389,842383,842779,844532,847465,...,-3.597147,0.793309,-5.177843,3.670753,-0.035073,0.392800,4.921409,-0.922877,8.607071,4.912855
Arkansas,150,9,21,15,269,807152,807193,810664,822608,833594,...,18.012611,15.487208,19.531981,14.860365,18.764610,25.429853,23.248130,27.588498,23.927394,27.755652
Iowa,150,6,12,57,429,807090,807085,809690,818946,828206,...,10.224301,7.367100,8.578369,8.213186,4.478413,15.126672,12.542500,14.133403,14.492295,10.682602
Idaho,150,12,24,48,83,719782,719782,721774,733583,745076,...,21.156309,20.416523,39.282258,40.029875,38.329324,23.136657,22.690841,41.716974,42.887869,41.265480
Maine,150,3,3,69,55,632728,632727,632530,634807,636742,...,5.439338,2.332435,1.893981,7.760245,-2.475211,8.652369,5.680685,5.444405,11.790245,1.571928
District of Columbia,50,3,5,11,1,601723,601767,605126,620472,635342,...,11.560071,10.052444,9.457678,1.480094,5.601833,17.028422,15.972111,15.634120,8.378037,12.434838
Mississippi,150,9,18,84,129,593642,593734,595385,603181,608248,...,18.479441,6.651550,-2.395420,2.685593,1.504391,21.165781,12.097544,1.561792,6.668289,6.057987
Alaska,150,12,27,6,280,478402,478402,481455,486320,492774,...,-8.076675,9.340896,-0.202602,-37.325733,-14.942448,-3.369482,20.270363,8.656139,-29.008088,-4.915660
West Virginia,150,9,15,162,53,393551,393546,393954,394211,396034,...,3.109074,9.276608,6.071358,3.327349,-2.494480,5.187991,11.942221,8.668154,6.330484,0.502821
Montana,150,12,24,90,203,348199,348199,348729,351209,354610,...,6.891466,13.742662,22.238780,23.008659,22.233419,8.836465,15.110271,23.773530,24.801700,23.985999
South Dakota,150,6,12,138,285,315244,315236,316548,321222,328352,...,25.027157,38.457869,39.009049,31.555417,10.483546,29.199692,43.623685,43.560252,36.495586,15.464339
North Dakota,150,6,12,114,67,297947,297947,298983,303074,311033,...,2.692011,38.785415,56.880875,25.875697,25.419591,10.020265,48.809998,66.553192,36.216662,35.774480
Vermont,150,3,3,150,51,277721,277712,277960,278568,279025,...,-5.090284,-10.625325,-6.050549,-11.464772,-15.602828,-2.099284,-6.866927,-2.110827,-6.866679,-10.977152
Wyoming,150,12,24,168,51,213321,213464,213987,215683,221474,...,3.145411,54.214456,23.214178,-10.735517,11.134846,4.066748,57.222746,25.171833,-8.827814,13.445908

In [270]:
def answer_six():
    counties = census_df[census_df["SUMLEV"] != 40].sort_values(by="CENSUS2010POP", \
            ascending=False).groupby('STNAME').head(3).groupby('STNAME').sum()
    return counties.sort_values(by="CENSUS2010POP", ascending=False).head(3).index.values

In [273]:
answer_six()

array(['California', 'Texas', 'Illinois'], dtype=object)

In [274]:
type(answer_six())

numpy.ndarray

In [282]:
def answer_six():
    counties = census_df[census_df["SUMLEV"] != 40].sort_values(by="CENSUS2010POP", \
            ascending=False).groupby('STNAME').head(3).groupby('STNAME').sum()
    return counties.sort_values(by="CENSUS2010POP", ascending=False).head(3)

In [290]:
result = answer_six()
result.index.values.tolist()

['California', 'Texas', 'Illinois']

In [289]:
result['STNAME']

KeyError: 'STNAME'